### ISSUE TITLE
Full CursorWindows and wrong Cursor initialization

### ISSUE THREAD

**Issue by Instinctlol** [yigit/android-priority-jobqueue#115]
I had a Job configuration which used persistence with android.util.Pair Objects.
However, android.util.Pair does not implement a Serialization Interface, so I just created my own Pair, which consists of 2 Strings.

Then this happened [(Pastebin)](http://pastebin.com/raw/cgPdAQWc):
`03-18 21:32:08.310 13147-13305/instinctlol.com.myproject W/CursorWindow: Window is full: requested allocation 4505792 bytes, free space 2096545 bytes, window size 2097152 bytes
03-18 21:32:08.381 13147-13305/instinctlol.com.myproject W/CursorWindow: Window is full: requested allocation 4505792 bytes, free space 2096545 bytes, window size 2097152 bytes
03-18 21:32:08.388 13147-13305/instinctlol.com.myproject E/CursorWindow: Failed to read row 0, column 5 from a CursorWindow which has 0 rows, 11 columns.
03-18 21:32:08.392 13147-13305/instinctlol.com.myproject E/AndroidRuntime: FATAL EXCEPTION: job-manager
                                                                           Process: instinctlol.com.myproject, PID: 13147
                                                                           java.lang.IllegalStateException: Couldn't read row 0, col 5 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
                                                                               at android.database.CursorWindow.nativeGetBlob(Native Method)
                                                                               at android.database.CursorWindow.getBlob(CursorWindow.java:403)
                                                                               at android.database.AbstractWindowedCursor.getBlob(AbstractWindowedCursor.java:45)
                                                                               at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.createJobHolderFromCursor(SqliteJobQueue.java:365)
                                                                               at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.nextJobAndIncRunCount(SqliteJobQueue.java:251)
                                                                               at com.path.android.jobqueue.cachedQueue.CachedJobQueue.nextJobAndIncRunCount(CachedJobQueue.java:76)
                                                                               at com.birbit.android.jobqueue.JobManagerThread.getNextJob(JobManagerThread.java:646)
                                                                               at com.birbit.android.jobqueue.JobManagerThread.getNextJob(JobManagerThread.java:625)
                                                                               at com.birbit.android.jobqueue.ConsumerManager.handleIdle(ConsumerManager.java:180)
                                                                               at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:224)
                                                                               at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
                                                                               at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:216)
                                                                               at java.lang.Thread.run(Thread.java:818)
03-18 21:32:08.541 13147-13194/instinctlol.com.myproject E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb878d910`

Which happens everytime I open my Activity which launches the jobs.

Then I changed the Job so it doesnt use persistence anymore. Then I called `destroy()` on my `ProjectManager` instance. Everytime I open the Activity its throwing `Failed to read row 0, column 5 from a CursorWindow which has 0 rows, 11 columns.`

So yeah.. How do I clean this up?

EDIT: Nevermind, manually uninstalling the app helped. But can you help me anyway?
How do I best use persistence with two fairly large ArrayLists of type String (each 112 elements)? I tried pairing the lists into one ArrayList because I dont want to iterate through both of them with indexes.

**Comment by yigit** [comment]
Hmm unfortunately this is not a limit jobqueue can work around. Though I've been thinking about moving serialized job data outside the sqlite database. This is another reason to do that.
Until then though, you can persist that data into a file and then keep the file path as a field in your job. You'll have to take care of file cleanup so it is not pretty but a potential workaround for this kind of situations.

**Comment by Instinctlol** [comment]
Thank you so much for your answer, I will probably use the file option to use persistence.

**Comment by yigit** [comment]
FYI, since alpha 4, jobs are kept in files which should fix your issue.
