### ISSUE TITLE
V2 - Unit test

### ISSUE THREAD

**Issue by emce** [yigit/android-priority-jobqueue#132]
Hey - I cannot pass this error:
```
Exception in thread "job-manager" android.database.sqlite.SQLiteException: Cannot prepare statement, base error code: -92
```
I have configured my test this way:
```
Configuration config = new Configuration.Builder(RuntimeEnvironment.application)
        .inTestMode()
        .id(UUID.randomUUID().toString())
        .minConsumerCount(1)
        .maxConsumerCount(3)
        .loadFactor(3)
        .consumerKeepAlive(120)
        .build();
```

**Comment by yigit** [comment]
Can you share the stack trace & branch (master?) ?

**Comment by emce** [comment]
Version 2 from maven, here's stacktrace:
```
Exception in thread "job-manager" android.database.sqlite.SQLiteException: Cannot prepare statement, base error code: -92
	at org.robolectric.shadows.ShadowSQLiteConnection.rethrow(ShadowSQLiteConnection.java:56)
	at org.robolectric.shadows.ShadowSQLiteConnection.access$500(ShadowSQLiteConnection.java:33)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.execute(ShadowSQLiteConnection.java:466)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections.prepareStatement(ShadowSQLiteConnection.java:376)
	at org.robolectric.shadows.ShadowSQLiteConnection.nativePrepareStatement(ShadowSQLiteConnection.java:67)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.__constructor__(SQLiteProgram.java:58)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java)
	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java)
	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
	at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)
	at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.nextJobAndIncRunCount(SqliteJobQueue.java:246)
	at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.nextJobAndIncRunCount(CachedJobQueue.java:76)
	at com.birbit.android.jobqueue.JobManagerThread.getNextJob(JobManagerThread.java:642)
	at com.birbit.android.jobqueue.JobManagerThread.getNextJob(JobManagerThread.java:621)
	at com.birbit.android.jobqueue.ConsumerManager.handleIdle(ConsumerManager.java:184)
	at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:220)
	at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
	at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:212)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.almworks.sqlite4java.SQLiteException: [-92] DB[1] is not confined or already disposed
	at com.almworks.sqlite4java.SQLiteConnection.checkThread(SQLiteConnection.java:1386)
	at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:451)
	at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:542)
	at com.almworks.sqlite4java.SQLiteConnection.prepare(SQLiteConnection.java:529)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$2.call(ShadowSQLiteConnection.java:380)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$2.call(ShadowSQLiteConnection.java:376)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$6.call(ShadowSQLiteConnection.java:452)
	at org.robolectric.shadows.ShadowSQLiteConnection$Connections$6.call(ShadowSQLiteConnection.java:446)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
```

**Comment by yigit** [comment]
Does this happen when you try to run a second test?

Also, which version of Robolectric is this?
I use robolectric 3.0 for job manager tests so it should work fine.

This is the cleanup Rule I use, maybe you can modify it to work for your project:

https://github.com/yigit/android-priority-jobqueue/blob/7d5ad191372eb445a576184de32204956d10c9ef/jobqueue/src/test/java/com/birbit/android/jobqueue/testing/CleanupRule.java

**Comment by emce** [comment]
I'm not directly testing JobManager, it's an object in one of my objects

**Comment by yigit** [comment]
well once constructed you have to either destroy the previous one or re-use it. Seems like robolectric does not handle in memory database well.

**Comment by emce** [comment]
It doesn't handle both kinds.. I can't pass through this...

**Comment by emce** [comment]
To be honest the problem is initialization, not instances...

**Comment by yigit** [comment]
which robolectric version are you using? I'm sure job manager can work with robolectric since it uses robolectric to run tests.

**Comment by emce** [comment]
it's 3.0.
