### ISSUE TITLE
Couldn't read row X, col Y from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it.

### ISSUE THREAD

**Issue by eddnav** [yigit/android-priority-jobqueue#154]
I'm getting two different issues with the almost the same crash, granted we still haven't updated to V2 we are using `1.1.2`, but the issues are fairly recent, any idea what could be happening? here are some stack traces:

1.
```
Fatal Exception: java.lang.IllegalStateException: Couldn't read row 0, col 4 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
       at android.database.CursorWindow.nativeGetBlob(CursorWindow.java)
       at android.database.CursorWindow.getBlob(CursorWindow.java:403)
       at android.database.AbstractWindowedCursor.getBlob(AbstractWindowedCursor.java:45)
       at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.createJobHolderFromCursor(SqliteJobQueue.java:292)
       at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.nextJobAndIncRunCount(SqliteJobQueue.java:204)
       at com.path.android.jobqueue.cachedQueue.CachedJobQueue.nextJobAndIncRunCount(CachedJobQueue.java:68)
       at com.path.android.jobqueue.JobManager.getNextJob(JobManager.java:273)
       at com.path.android.jobqueue.JobManager.access$400(JobManager.java:25)
       at com.path.android.jobqueue.JobManager$2.getNextJob(JobManager.java:412)
       at com.path.android.jobqueue.executor.JobConsumerExecutor$JobConsumer.run(JobConsumerExecutor.java:198)
       at java.lang.Thread.run(Thread.java:818)
```

2.
```
Fatal Exception: java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
       at android.database.CursorWindow.nativeGetLong(CursorWindow.java)
       at android.database.CursorWindow.getLong(CursorWindow.java:511)
       at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
       at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
       at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.nextJobAndIncRunCount(SqliteJobQueue.java:201)
       at com.path.android.jobqueue.cachedQueue.CachedJobQueue.nextJobAndIncRunCount(CachedJobQueue.java:68)
       at com.path.android.jobqueue.JobManager.getNextJob(JobManager.java:273)
       at com.path.android.jobqueue.JobManager.access$400(JobManager.java:25)
       at com.path.android.jobqueue.JobManager$2.getNextJob(JobManager.java:412)
       at com.path.android.jobqueue.executor.JobConsumerExecutor$JobConsumer.run(JobConsumerExecutor.java:198)
       at java.lang.Thread.run(Thread.java:818)
```

This second issue is currently only reported on Android 6 and 6.0.1 devices.

Appreciate any help, thanks.

**Comment by yigit** [comment]
by any change are you putting too big data in your persistent jobs? CursorWindow has a 2mb limit, if you are going over that, you might be receiving these reports.

**Comment by eddnav** [comment]
I'll check this, thanks for your reply.

**Comment by yigit** [comment]
2.0 alpha-4 keeps job data in files so this should not be an issue anymore.
