### ISSUE TITLE
Cursor window allocation of 2048 kb failed

### ISSUE THREAD

**Issue by ajgarn** [yigit/android-priority-jobqueue#183]
I'm running version 1.3.5 and encountered this problem.

```
android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
	at android.database.CursorWindow.(CursorWindow.java:104)
	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
	at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.findJobsByTags(SqliteJobQueue.java:256)
	at com.path.android.jobqueue.cachedQueue.CachedJobQueue.findJobsByTags(CachedJobQueue.java:105)
	at com.path.android.jobqueue.JobManager$2.run(JobManager.java:312)
	at com.path.android.jobqueue.executor.JobConsumerExecutor.inRunningJobHoldersLock(JobConsumerExecutor.java:175)
	at com.path.android.jobqueue.JobManager.cancelJobs(JobManager.java:288)
	at se.electra.butikstv.jobs.core.CustomJobManager.cancelJobs(CustomJobManager.java:40)
	at com.path.android.jobqueue.JobManager$1.run(JobManager.java:241)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:856)
```

My `CustomJobManager` just calls `super.cancelJobs(...)`. Do you have any idea of what the problem could be?

**Comment by yigit** [comment]
this happens when your jobs get too big. (e.g. you put a bitmap in it.), It was never part of the initial design.
In v2, this will be fixed because persistent jobs will be saved in separate files on disk. (metadata is still in sql). Master branch has this implementation and will be released in alpha4. see #175

**Comment by ajgarn** [comment]
Ok, thank you very much!
