### ISSUE TITLE
android.database.sqlite.SQLiteCantOpenDatabaseException

### ISSUE THREAD

**Issue by Vivecstel** [yigit/android-priority-jobqueue#189]
Hello,

I am getting the following exception from time to time :

06-19 12:36:50.529 17405-17437/com.steleot.seriez E/SQLiteLog: (14) cannot open file at line 31278 of [2ef4f3a5b1]
06-19 12:36:50.529 17405-17437/com.steleot.seriez E/SQLiteLog: (14) os_unix.c:31278: (24) open(/data/user/0/com.steleot.seriez/databases/Seriez.db-journal) - 
06-19 12:36:50.529 17405-17437/com.steleot.seriez E/SQLiteLog: (14) cannot open file at line 31278 of [2ef4f3a5b1]
06-19 12:36:50.529 17405-17437/com.steleot.seriez E/SQLiteLog: (14) os_unix.c:31278: (24) open(/data/user/0/com.steleot.seriez/databases/Seriez.db-journal) - 
06-19 12:36:50.529 17405-17437/com.steleot.seriez E/SQLiteLog: (14) unable to open database file
06-19 12:36:50.530 17405-17742/com.steleot.seriez D/Seriez: Select series with onlyInSearch : false and order by : seriesName asc
06-19 12:36:50.530 17405-17433/com.steleot.seriez E/SQLiteLog: (14) cannot open file at line 31278 of [2ef4f3a5b1]
06-19 12:36:50.530 17405-17433/com.steleot.seriez E/SQLiteLog: (14) os_unix.c:31278: (24) open(/data/user/0/com.steleot.seriez/databases/db_default_job_manager-journal) - 
06-19 12:36:50.530 17405-17433/com.steleot.seriez E/SQLiteLog: (14) cannot open file at line 31278 of [2ef4f3a5b1]
06-19 12:36:50.530 17405-17433/com.steleot.seriez E/SQLiteLog: (14) os_unix.c:31278: (24) open(/data/user/0/com.steleot.seriez/databases/db_default_job_manager-journal) - 
06-19 12:36:50.530 17405-17433/com.steleot.seriez E/SQLiteLog: (14) statement aborts at 125: [SELECT * FROM (SELECT deadline FROM job_holder WHERE ( (deadline != 9223372036854775807 AND deadline <= ?) OR network_type <= ?) AND running_session_id != ? ORDER BY 1 ASC LIMIT 1) UN
06-19 12:36:50.530 17405-17742/com.steleot.seriez E/SQLiteLog: (14) cannot open file at line 31278 of [2ef4f3a5b1]
06-19 12:36:50.530 17405-17742/com.steleot.seriez E/SQLiteLog: (14) os_unix.c:31278: (24) open(/data/user/0/com.steleot.seriez/databases/Seriez.db) - 
06-19 12:36:50.549 17405-17433/com.steleot.seriez E/UncaughtException: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
                                                                           at android.database.sqlite.SQLiteConnection.nativeExecuteForLong(Native Method)
                                                                           at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:596)
                                                                           at android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:652)
                                                                           at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:107)
                                                                           at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.getNextJobDelayUntilNs(SqliteJobQueue.java:322)
                                                                           at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.getNextJobDelayUntilNs(CachedJobQueue.java:88)
                                                                           at com.birbit.android.jobqueue.JobManagerThread.getNextWakeUpNs(JobManagerThread.java:599)
                                                                           at com.birbit.android.jobqueue.JobManagerThread$1.onIdle(JobManagerThread.java:260)
                                                                           at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.next(PriorityMessageQueue.java:89)
                                                                           at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:36)
                                                                           at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:220)
                                                                           at java.lang.Thread.run(Thread.java:818)
06-19 12:36:50.555 17405-17742/com.steleot.seriez E/SQLiteDatabase: Failed to open database '/data/user/0/com.steleot.seriez/databases/Seriez.db'.
                                                                    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
                                                                        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
                                                                        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:207)
                                                                        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:191)
                                                                        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
                                                                        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
                                                                        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
                                                                        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
                                                                        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
                                                                        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
                                                                        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:571)
                                                                        at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:269)
                                                                        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
                                                                        at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
                                                                        at com.steleot.seriez.database.DatabaseHelper.getSeries(DatabaseHelper.java:1003)
                                                                        at com.steleot.seriez.database.DatabaseHelper.getSeriesOrderByNameAsc(DatabaseHelper.java:987)
                                                                        at com.steleot.seriez.utils.JobsUtils.getSeriesListFromDatabase(JobsUtils.java:679)
                                                                        at com.steleot.seriez.utils.JobsUtils.getSeries(JobsUtils.java:644)
                                                                        at com.steleot.seriez.jobs.HomeRecentJob.doRun(HomeRecentJob.java:43)
                                                                        at com.steleot.seriez.jobs.base.BasicJob.onRun(BasicJob.java:47)
                                                                        at com.birbit.android.jobqueue.Job.safeRun(Job.java:229)
                                                                        at com.birbit.android.jobqueue.JobHolder.safeRun(JobHolder.java:132)
                                                                        at com.birbit.android.jobqueue.ConsumerManager$Consumer.handleRunJob(ConsumerManager.java:398)
                                                                        at com.birbit.android.jobqueue.ConsumerManager$Consumer.access$000(ConsumerManager.java:317)
                                                                        at com.birbit.android.jobqueue.ConsumerManager$Consumer$2.handleMessage(ConsumerManager.java:345)
                                                                        at com.birbit.android.jobqueue.messaging.SafeMessageQueue.consume(SafeMessageQueue.java:36)
                                                                        at com.birbit.android.jobqueue.ConsumerManager$Consumer.run(ConsumerManager.java:380)
                                                                        at java.lang.Thread.run(Thread.java:818)

**Comment by yigit** [comment]
not sure if this is related to job manager because there are two db open errors in your log:
/data/user/0/com.steleot.seriez/databases/Seriez.db
/data/user/0/com.steleot.seriez/databases/Seriez.db-journal

Seems like your app lost access to the disk. Do you have information from the error log ?

**Comment by Vivecstel** [comment]
Problem was unrelated to android priority jobqueue. Changed my application database library to green dao but still got the exception. So i limited the database access from the background threads and now seems ok.

Thanks :)
