### ISSUE TITLE
SQLiteException: no such table: job_holder

### ISSUE THREAD

**Issue by tmelz** [yigit/android-priority-jobqueue#191]
Seeing a report of this on a Huawei Nexus 6P running API 24. We're using `    compile 'com.birbit:android-priority-jobqueue:1.3.5'`.
```
Fatal Exception: android.database.sqlite.SQLiteException: no such table: job_holder (code 1)
       at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
       at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
       at android.database.AbstractCursor.moveToNext(AbstractCursor.java:268)
       at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.countReadyJobs(SqliteJobQueue.java:196)
       at com.path.android.jobqueue.cachedQueue.CachedJobQueue.countReadyJobs(CachedJobQueue.java:59)
       at com.path.android.jobqueue.JobManager.countReadyJobs(JobManager.java:148)
       at com.path.android.jobqueue.JobManager.access$400(JobManager.java:32)
       at com.path.android.jobqueue.JobManager$5.countRemainingReadyJobs(JobManager.java:756)
       at com.path.android.jobqueue.executor.JobConsumerExecutor.isAboveLoadFactor(JobConsumerExecutor.java:102)
       at com.path.android.jobqueue.executor.JobConsumerExecutor.doINeedANewThread(JobConsumerExecutor.java:69)
       at com.path.android.jobqueue.executor.JobConsumerExecutor.canIDie(JobConsumerExecutor.java:53)
       at com.path.android.jobqueue.executor.JobConsumerExecutor.access$200(JobConsumerExecutor.java:23)
       at com.path.android.jobqueue.executor.JobConsumerExecutor$JobConsumer.run(JobConsumerExecutor.java:329)
       at java.lang.Thread.run(Thread.java:761)
```

**Comment by yigit** [comment]
Hmm, we don't really drop a table after it is created. Do you have any idea on how to reproduce this ?

**Comment by yigit** [comment]
v2 is released so closing this.
