### ISSUE TITLE
IllegalStateException : Couldn't read row 0, col 0 from CursorWindow

### ISSUE THREAD

**Issue by yigit** [yigit/android-priority-jobqueue#2]
_From @AndroidDeveloperLB on February 17, 2015 15:21_

I got this weird exception, which I can't even find its cause because the library got obfuscated:

java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
       at android.database.CursorWindow.nativeGetLong(CursorWindow.java)
       at android.database.CursorWindow.getLong(CursorWindow.java:511)
       at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
       at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
       at com.path.android.jobqueue.h.a.d.b(SqliteJobQueue.java:201)
       at com.path.android.jobqueue.a.a.b(CachedJobQueue.java:68)
       at com.path.android.jobqueue.f.d(JobManager.java:273)
       at com.path.android.jobqueue.f.c(JobManager.java:25)
       at com.path.android.jobqueue.h.a(JobManager.java:412)
       at com.path.android.jobqueue.d.a$b.run(JobConsumerExecutor.java:198)
       at java.lang.Thread.run(Thread.java:841)

Any way to find why it occurs, and how to fix it?

_Copied from original issue: path/android-priority-jobqueue#95_

**Comment by yigit** [comment]
_From @LOG-TAG on March 3, 2015 7:44_

may be this is the issue https://github.com/path/android-priority-jobqueue/issues/55

**Comment by yigit** [comment]
_From @AndroidDeveloperLB on March 3, 2015 8:6_

I don't see this exception there. Are you sure it can be it?

**Comment by yigit** [comment]
Hmm, weird. Is this something you can reproduce?

Also, there is no reason to obfuscate the library since it is open source anyways. You can also resolve it using the obfuscation output of proguard.

**Comment by AndroidDeveloperLB** [comment]
I will check it out in the coming month, I hope.

**Comment by yigit** [comment]
yes I'm the original author of this library but I no more work for Path and there were some problems me committing there. So I forked it and continuing development here.

see for details:
https://github.com/path/android-priority-jobqueue/issues/96

**Comment by AndroidDeveloperLB** [comment]
ok, thank you. You can also check my repos if you wish. :)

**Comment by lxalln** [comment]
I am getting this issue as well
```
java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it.
at android.database.CursorWindow.nativeGetLong(Native Method)
at android.database.CursorWindow.getLong(CursorWindow.java)
at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java)
at android.database.AbstractCursor.moveToPosition(AbstractCursor.java)
at android.database.AbstractCursor.moveToNext(AbstractCursor.java)
at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.nextJobAndIncRunCount(SqliteJobQueue.java:201)
at com.path.android.jobqueue.cachedQueue.CachedJobQueue.nextJobAndIncRunCount(CachedJobQueue.java:68)
at com.path.android.jobqueue.JobManager.getNextJob(JobManager.java:273)
at com.path.android.jobqueue.JobManager.access$400(JobManager.java:25)
at com.path.android.jobqueue.JobManager$2.getNextJob(JobManager.java:423)
at com.path.android.jobqueue.executor.JobConsumerExecutor$JobConsumer.run(JobConsumerExecutor.java:198)
at java.lang.Thread.run(Thread.java:818)
```

Without forking the project and attempting a fix (not sure where to begin), is there any way to work around this? I'm not sure if there is even somewhere I can catch the exception to stop it crashing my application.

I'm unsure why the cursor wouldn't be initialized correctly, but maybe it's worth handling this scenario a little easier?

It seems to be happening in this [method](https://github.com/yigit/android-priority-jobqueue/blame/master/jobqueue/src/main/java/com/path/android/jobqueue/persistentQueue/sqlite/SqliteJobQueue.java#L388) any ideas?

**Comment by yigit** [comment]
@lxalln is it something you can reproduce? 
The problem is happening when we try to move the cursor to the first item, after receiving it. 

Google'ing the exception shows this:
http://stackoverflow.com/questions/21432556/android-java-lang-illegalstateexception-couldnt-read-row-0-col-0-from-cursorw

By any chance, do you have a huge job causing this? e.g. are you trying to serialize a bitmap inside a job?

**Comment by AndroidDeveloperLB** [comment]
I don't think I got this exception ever since I've used this repo.

**Comment by yigit** [comment]
@AndroidDeveloperLB , I didn't really fix anything related to this (unless it is fixed by chance, which i don't think so). The SO link makes a lot of sense though :). Maybe your jobs got smaller ?

**Comment by AndroidDeveloperLB** [comment]
I have no idea. I work more on the frontend, and less on the backend of the
app, but I do handle bugs there from time to time.

**Comment by lxalln** [comment]
@yigit unfortunately I haven't been able to reproduce it, I'm just getting crash reports from our Android app. I doubt it'd be job size, we don't have much more than a few strings, certainly nothing as large as a bitmap. I'll double check just to be sure.

**Comment by TheLester** [comment]
@lxalln  Have you solved your problem? I have the same issue, my job contains byte array ,it may be large, but i store this byte array as blob in my own sqlite db , and it querying normal...

**Comment by yigit** [comment]
@lxalln Keep in mind that there is additional payload when the whole job is serialized so you may as well be close to the limit and this extra data maybe pushing you above the threshold. This is a platform limitation, nothing much JobManager can do unless we create a new API for extra payloads managed in filesystem. Which, actually sounds like a good idea :).

**Comment by lxalln** [comment]
@TheLester @yigit  We solved the problem, but only by disabling persistence on all jobs, which isn't too bad for our app, not ideal, but not the end of the world. I double checked the jobs, there was certainly no large jobs.

**Comment by yigit** [comment]
I realized I referenced @lxalln but my intention was @TheLester  :/.
@lxalln I'm sorry to hear that. Are those jobs contain data fully constructed by you or do they happen to include any unbound user data?

**Comment by lxalln** [comment]
@yigit some of the jobs have user data, so I suppose there could be an issue. It isn't expected to be large amount of data, but obviously that doesn't rule out them entering lots of data.

**Comment by yigit** [comment]
jobs are saved into files in v2 so should not see this error anymore.
