### ISSUE TITLE
A resource was acquired at attached stack trace but never released

### ISSUE THREAD

**Issue by mseshachalam** [yigit/android-priority-jobqueue#206]
I am using  'com.birbit:android-priority-jobqueue:2.0.0-beta1' and the same jobs when not mentioned as persist works fine. 

```
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                                         java.lang.Throwable: Explicit termination method 'close' not called
                                                                             at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                                             at android.database.CursorWindow.<init>(CursorWindow.java:111)
                                                                             at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
                                                                             at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
                                                                             at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
                                                                             at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.loadTags(SqliteJobQueue.java:439)
                                                                             at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.createJobHolderFromCursor(SqliteJobQueue.java:416)
                                                                             at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.nextJobAndIncRunCount(SqliteJobQueue.java:294)
                                                                             at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.nextJobAndIncRunCount(CachedJobQueue.java:79)
                                                                             at com.birbit.android.jobqueue.JobManagerThread.getNextJob(JobManagerThread.java:652)
                                                                             at com.birbit.android.jobqueue.JobManagerThread.getNextJob(JobManagerThread.java:629)
                                                                             at com.birbit.android.jobqueue.ConsumerManager.handleIdle(ConsumerManager.java:190)
                                                                             at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:228)
                                                                             at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
                                                                             at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:220)
                                                                             at java.lang.Thread.run(Thread.java:818)
07-18 13:55:58.145 20203-20213/com.abbiya.android.superset E/StrictMode: Finalizing a Cursor that has not been deactivated or closed. database = /data/data/com.abbiya.android.superset/databases/db_default_job_manager, table = null, query = SELECT tag_name FROM job_holder_tags WHERE job_id = ?
                                                                         android.database.sqlite.DatabaseObjectNotClosedException: Application did not close the cursor or database object that was opened here
                                                                             at android.database.sqlite.SQLiteCursor.<init>(SQLiteCursor.java:98)
                                                                             at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:50)
                                                                             at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
                                                                             at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)
                                                                             at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.loadTags(SqliteJobQueue.java:438)
                                                                             at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.createJobHolderFromCursor(SqliteJobQueue.java:416)
                                                                             at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.nextJobAndIncRunCount(SqliteJobQueue.java:294)
                                                                             at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.nextJobAndIncRunCount(CachedJobQueue.java:79)
                                                                             at com.birbit.android.jobqueue.JobManagerThread.getNextJob(JobManagerThread.java:652)
                                                                             at com.birbit.android.jobqueue.JobManagerThread.getNextJob(JobManagerThread.java:629)
                                                                             at com.birbit.android.jobqueue.ConsumerManager.handleIdle(ConsumerManager.java:190)
                                                                             at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:228)
                                                                             at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
                                                                             at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:220)
                                                                             at java.lang.Thread.run(Thread.java:818)

```

**Comment by yigit** [comment]
Thanks for the report. This will be out with beta2, meanwhile, you can use jitpack.
