### ISSUE TITLE
persist() parameter fails to work

### ISSUE THREAD

**Issue by leibovic** [yigit/android-priority-jobqueue#228]
I'm new to using this library, so forgive me if I'm doing something wrong, but attempting to create a new Job with the `persist()` parameter is resulting in the crash below (using beta3).

Am I supposed to provide my own serialization logic for these jobs? Or is something else going wrong here? I don't see any additional logic in the sample app code:
https://github.com/yigit/android-priority-jobqueue/blob/master/examples/twitter/TwitterClient/src/com/birbit/android/jobqueue/examples/twitter/jobs/PostTweetJob.java#L25

> E/AndroidRuntime: FATAL EXCEPTION: job-manager
 Process: <my process>, PID: 9211
 java.lang.RuntimeException: cannot save job to disk
     at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.persistJobToDisk(SqliteJobQueue.java:107)
     at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.insert(SqliteJobQueue.java:90)
     at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.insert(CachedJobQueue.java:29)
     at com.birbit.android.jobqueue.JobManagerThread.handleAddJob(JobManagerThread.java:141)
     at com.birbit.android.jobqueue.JobManagerThread.access$000(JobManagerThread.java:35)
     at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:225)
     at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
     at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:220)
     at java.lang.Thread.run(Thread.java:818)
  Caused by: java.io.NotSerializableException: <my class>
     at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
     at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
     at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
     at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
     at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
     at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
     at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
     at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
     at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue$JavaSerializer.serialize(SqliteJobQueue.java:493)
     at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.persistJobToDisk(SqliteJobQueue.java:105)
     at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.insert(SqliteJobQueue.java:90) 
     at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.insert(CachedJobQueue.java:29) 
     at com.birbit.android.jobqueue.JobManagerThread.handleAddJob(JobManagerThread.java:141) 
     at com.birbit.android.jobqueue.JobManagerThread.access$000(JobManagerThread.java:35) 
     at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:225) 
     at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39) 
     at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:220) 
     at java.lang.Thread.run(Thread.java:818) 

Here is my Job code:

    private class SendMessageJob extends Job {

        SendMessageJob() {
            super(new Params(0).requireNetwork().persist());
        }

        @Override
        public void onAdded() {

        }

        @Override
        public void onRun() throws Throwable {
            // ... do some API call
        }

        @Override
        protected void onCancel(int cancelReason, @Nullable Throwable throwable) {

        }

        @Override
        protected RetryConstraint shouldReRunOnThrowable(@NonNull Throwable throwable, int runCount, int maxRunCount) {
            return null;
        }
    }

**Comment by yigit** [comment]
Can you share the rest of your job. I'm guessing you have a non-serializable field in the job (although it should be in the logs :/).

**Comment by yigit** [comment]
oh wait, i just realized your class is private. That won't work since we have to deserialize from the disk. You must make the class public.

**Comment by leibovic** [comment]
@yigit Thanks for your response. I had created the job as an inner class, but pulling it out into a separate public class fixed my issue.

**Comment by sandeep-agrawal** [comment]
@yigit My model class has implemented the parable and when I try to use .persist in job, it is crashing wtih NotSerializableException. Do I need to make any changes to use parcable class?
