### ISSUE TITLE
App crashes on first launch after update from 2.0.0-beta2 to 2.0.0

### ISSUE THREAD

**Issue by z0idberg** [yigit/android-priority-jobqueue#233]
If I update JobQueue in my app from 2.0.0-beta2 to 2.0.0 then the app crashes on first launch of the updated version. The next launch the error does not occur. Seems like there is some SQLite migration issue.
```
java.lang.RuntimeException: Unable to create application ru.softinvent.myapp.MyApp: android.database.sqlite.SQLiteException: duplicate column name: cancelled (code 1)
     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4556)
     at android.app.ActivityThread.access$1500(ActivityThread.java:151)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:135)
     at android.app.ActivityThread.main(ActivityThread.java:5254)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
  Caused by: android.database.sqlite.SQLiteException: duplicate column name: cancelled (code 1)
     at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
     at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
     at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
     at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
     at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1676)
     at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605)
     at com.birbit.android.jobqueue.persistentQueue.sqlite.DbOpenHelper.addCancelColumn(DbOpenHelper.java:84)
     at com.birbit.android.jobqueue.persistentQueue.sqlite.DbOpenHelper.onUpgrade(DbOpenHelper.java:72)
     at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
     at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
     at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.<init>(SqliteJobQueue.java:49)
     at com.birbit.android.jobqueue.DefaultQueueFactory.createPersistentQueue(DefaultQueueFactory.java:27)
     at com.birbit.android.jobqueue.JobManagerThread.<init>(JobManagerThread.java:85)
     at com.birbit.android.jobqueue.JobManager.<init>(JobManager.java:62)
     at ru.softinvent.myapp.MyApp.initJobQueue(MyApp.java:248)
     at ru.softinvent.myapp.MyApp.onCreate(MyApp.java:144)
     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
```

Initialization code:

```java
private void initJobQueue() {
  Configuration configuration = new Configuration.Builder(this)
      .customLogger(new CustomLogger() {
        private static final String TAG = "JOBS ";
          @Override
          public boolean isDebugEnabled() {
            return BuildConfig.DEBUG;
          }
          @Override
          public void d(String text, Object... args) {
            Log.d(BuildConfig.TAG, TAG + String.format(text, args));
          }
          @Override
          public void e(Throwable t, String text, Object... args) {
            Log.e(BuildConfig.TAG, TAG + String.format(text, args), t);
          }
          @Override
          public void e(String text, Object... args) {
            Log.e(BuildConfig.TAG, TAG + String.format(text, args));
          }
          @Override
          public void v(String text, Object... args) {
            Log.v(BuildConfig.TAG, TAG + String.format(text, args));
          }
        })
        .loadFactor(1)
        .build();
    jobManager = new JobManager(configuration);
  }
```

**Comment by yigit** [comment]
that is weird. beta2 already had that field :/ and migration only happens if previous db version is 11 which is beta1.
https://github.com/yigit/android-priority-jobqueue/commit/661d15849d40ceafbd4e6465abf4f1ee85e40a66

**Comment by yigit** [comment]
I was thinking about this, by any chance, did you install the older version on top of the new one then upgraded to the new one ?
