### ISSUE TITLE
Mysterious SQLiteException

### ISSUE THREAD

**Issue by optisamit** [yigit/android-priority-jobqueue#261]
```
E/AndroidRuntime: FATAL EXCEPTION: job-manager
                                                                android.database.sqlite.SQLiteException: cannot rollback - no transaction is active (code 1)
                                                                    at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
                                                                    at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:741)
                                                                    at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:439)
                                                                    at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
                                                                    at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:524)
                                                                    at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.delete(SqliteJobQueue.java:217)
                                                                    at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.nextJobAndIncRunCount(SqliteJobQueue.java:309)
                                                                    at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.nextJobAndIncRunCount(CachedJobQueue.java:79)
                                                                    at com.birbit.android.jobqueue.JobManagerThread.getNextJob(JobManagerThread.java:652)
                                                                    at com.birbit.android.jobqueue.JobManagerThread.getNextJob(JobManagerThread.java:629)
                                                                    at com.birbit.android.jobqueue.ConsumerManager.handleIdle(ConsumerManager.java:190)
                                                                    at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:228)
                                                                    at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
                                                                    at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:220)
                                                                    at java.lang.Thread.run(Thread.java:856)
```
It crashed all of a sudden, I can't tell any exact steps

**Comment by yigit** [comment]
that is weird :/. Can you reproduce or does it recover ?

**Comment by optisamit** [comment]
Unfortunately, it happened only once and I have no idea how to reproduce it.
