### ISSUE TITLE
NotSerializableException

### ISSUE THREAD

**Issue by jemshit** [yigit/android-priority-jobqueue#277]
My Job has this variables in it:

```java
    private static final String LOG_TAG = "ImageDownloadJob";
    private static final String GROUP = "image_download";
    @Inject OkHttpClient okHttpClient;
    private String imagePath,  imageName,  imageUrl, uId; 
    private int imageDatabaseType;
```

I got this error once:
```
FATAL EXCEPTION: job-manager
Process: com.pordiva.skylife.debug, PID: 14183
  java.lang.RuntimeException: cannot save job to disk
 at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.persistJobToDisk(SqliteJobQueue.java:107)
                                                                               at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.insertOrReplace(SqliteJobQueue.java:186)
                                                                               at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.insertOrReplace(CachedJobQueue.java:39)
                                                                               at com.birbit.android.jobqueue.JobManagerThread.reAddJob(JobManagerThread.java:550)
                                                                               at com.birbit.android.jobqueue.JobManagerThread.insertOrReplace(JobManagerThread.java:544)
                                                                               at com.birbit.android.jobqueue.JobManagerThread.handleRunJobResult(JobManagerThread.java:492)
                                                                               at com.birbit.android.jobqueue.JobManagerThread.access$300(JobManagerThread.java:35)
                                                                               at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:237)
                                                                               at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
                                                                               at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:222)
                                                                               at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.NotSerializableException: okhttp3.OkHttpClient
                                                                               at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
                                                                               at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                                               at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                                               at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                                               at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
                                                                               at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
                                                                               at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
                                                                               at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
                                                                               at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                                               at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                                               at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                                               at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue$JavaSerializer.serialize(SqliteJobQueue.java:493)
                                                                               at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.persistJobToDisk(SqliteJobQueue.java:105)
                                                                               at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.insertOrReplace(SqliteJobQueue.java:186) 
                                                                               at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.insertOrReplace(CachedJobQueue.java:39) 
                                                                               at com.birbit.android.jobqueue.JobManagerThread.reAddJob(JobManagerThread.java:550) 
                                                                               at com.birbit.android.jobqueue.JobManagerThread.insertOrReplace(JobManagerThread.java:544) 
                                                                               at com.birbit.android.jobqueue.JobManagerThread.handleRunJobResult(JobManagerThread.java:492) 
                                                                               at com.birbit.android.jobqueue.JobManagerThread.access$300(JobManagerThread.java:35) 
                                                                               at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:237) 
                                                                               at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39) 
                                                                               at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:222) 
```

As i understand my OkHttpClient object is not serializable. Does making `OkHttpClient` `transient` solve problem  or is there sth else i have to do ?

**Comment by yigit** [comment]
yes, you should make it transient since you are already injecting it. When job is deserialized to be re-run, it will be injected.
