### ISSUE TITLE
Inifinite Retry

### ISSUE THREAD

**Issue by jemshit** [yigit/android-priority-jobqueue#279]
I have this Initialization, Singleton:
```java
    @Provides
    @Singleton
    public JobManager provideJobManager() {
        JobManager jobManager;
        JobManagerLogger jobManagerLogger = new JobManagerLogger();
        JobCallback jobManagerCallback = new JobCallback();

        Configuration config = new Configuration.Builder(app)
                .minConsumerCount(1)
                .maxConsumerCount(3)
                .injector(new DependencyInjector() {
                    @Override
                    public void inject(Job job) {
                        if (job instanceof BaseJob) {
                            ((BaseJob) job).inject(app.getAppComponent());
                        }
                    }
                })
                .consumerKeepAlive(45)
                .build();
        jobManager=new JobManager(config);
        jobManager.addCallback(jobManagerCallback);

        return jobManager;
    }
```
I inject it in `Application` class:
```java
@Inject
JobManager jobManager;
```
Also inject it in imageDownload class.

I have this retry logic:
```java
@Override
    protected RetryConstraint shouldReRunOnThrowable(Throwable throwable, int runCount, int maxRunCount) {       
        if (throwable!=null && shouldRetry(throwable)) {
            // Just back off 5000 ms.
            RetryConstraint constraint = RetryConstraint
                    .createExponentialBackoff(2, 5000);
            constraint.setApplyNewDelayToGroup(false);
            return constraint;
        }else if(throwable==null){
            return RetryConstraint.RETRY;
        }
        return RetryConstraint.CANCEL;
    }
```
 
Logcat:
```java
JobManager: error while executing job com.pordiva.skylife.background_job.ImageDownloadJob@c26b8ea
                                                                       java.net.SocketTimeoutException
                                                                           at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
                                                                           at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:37)
                                                                           at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                                           at okio.Okio$2.read(Okio.java:138)
                                                                           at okio.AsyncTimeout$2.read(AsyncTimeout.java:238)
                                                                           at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
                                                                           at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
                                                                           at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
                                                                           at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
                                                                           at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
                                                                           at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:53)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                           at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                           at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                           at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                           at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                           at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
                                                                           at okhttp3.RealCall.execute(RealCall.java:60)
                                                                           at com.pordiva.skylife.background_job.ImageDownloadJob$override.onRun(ImageDownloadJob.java:97)
                                                                           at com.pordiva.skylife.background_job.ImageDownloadJob$override.access$dispatch(ImageDownloadJob.java)
                                                                           at com.pordiva.skylife.background_job.ImageDownloadJob.onRun(ImageDownloadJob.java:0)
                                                                           at com.birbit.android.jobqueue.Job.safeRun(Job.java:229)
                                                                           at com.birbit.android.jobqueue.JobHolder.safeRun(JobHolder.java:132)
                                                                           at com.birbit.android.jobqueue.ConsumerManager$Consumer.handleRunJob(ConsumerManager.java:407)
                                                                           at com.birbit.android.jobqueue.ConsumerManager$Consumer.access$000(ConsumerManager.java:326)
                                                                           at com.birbit.android.jobqueue.ConsumerManager$Consumer$2.handleMessage(ConsumerManager.java:354)
                                                                           at com.birbit.android.jobqueue.messaging.SafeMessageQueue.consume(SafeMessageQueue.java:36)
                                                                           at com.birbit.android.jobqueue.ConsumerManager$Consumer.run(ConsumerManager.java:389)
                                                                           at java.lang.Thread.run(Thread.java:818)
11-10 17:47:02.532 23153-23401/com.pordiva.skylife.debug D/MyCustomLog JobCallback: -------------------------------
                                                                                    onAfterJobRun
                                                                                    			 | resultCode: RESULT_FAIL_WILL_RETRY
```

i once saw `RESULT_CANCEL_REACHED_RETRY_LIMIT` after 10 minutes for only 1 job... Is there any problem with my retry logic? How many times does it retry ?

**Comment by jemshit** [comment]
I think i got to override this method in Job class.
```java
@Override
    protected int getRetryLimit() {
        return 2;
    }
```
You can close issue i am right

**Comment by yigit** [comment]
Retry delay starts after the job has failed so maybe the job takes ~10s to fail?

**Comment by jemshit** [comment]
Yep, i missed that point.
