### ISSUE TITLE
Fatal Exception: java.lang.InernalError

### ISSUE THREAD

**Issue by arijain28** [yigit/android-priority-jobqueue#294]
Fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:730)
       at com.birbit.android.jobqueue.ConsumerManager.addWorker(ConsumerManager.java:158)
       at com.birbit.android.jobqueue.ConsumerManager.considerAddingConsumers(ConsumerManager.java:142)
       at com.birbit.android.jobqueue.ConsumerManager.onJobAdded(ConsumerManager.java:95)
       at com.birbit.android.jobqueue.JobManagerThread.handleAddJob(JobManagerThread.java:159)
       at com.birbit.android.jobqueue.JobManagerThread.access$000(JobManagerThread.java:35)
       at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:225)
       at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
       at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:220)
       at java.lang.Thread.run(Thread.java:761

**Comment by yigit** [comment]
That is weird, are you trying to run some jobs when your app receives `UncaughtExceptionError` ?
Found this: https://github.com/square/okhttp/issues/1153

**Comment by arijain28** [comment]
Hi yigit, Any Update on this issue. The customers are facing this issue but I cannot reproduce it

**Comment by arijain28** [comment]
[com.adobe.sparklerandroid_issue_11_crash_586B329000D0000270561D082D350D33_8bce41104611426da3a7edb7f40c6aab_0_v1.txt](https://github.com/yigit/android-priority-jobqueue/files/681814/com.adobe.sparklerandroid_issue_11_crash_586B329000D0000270561D082D350D33_8bce41104611426da3a7edb7f40c6aab_0_v1.txt)

**Comment by yigit** [comment]
Hi, I'm on vacation right now but will go back soon and will try to release a version that prevents this crash the following weekend.

Btw, the exception is only happening because your app already crashed for some other reason (process is being killed) so this is likely preventing a real report (which is bad) but not causing the crash.
