### ISSUE TITLE
NPE Job.getSingleInstanceId()

### ISSUE THREAD

**Issue by channguyen** [yigit/android-priority-jobqueue#295]
Hi there, 

Just saw this issue from Fabric:
```
Fatal Exception: java.lang.NullPointerException
       at com.birbit.android.jobqueue.Job.getSingleInstanceId(Job.java:314)
       at com.birbit.android.jobqueue.JobManagerThread.handleAddJob(JobManagerThread.java:133)
       at com.birbit.android.jobqueue.JobManagerThread.access$000(JobManagerThread.java:35)
       at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:225)
       at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
       at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:220)
       at java.lang.Thread.run(Thread.java:841)
```
Have no idea what would cause job to be null? Any idea? Thanks!

**Comment by yigit** [comment]
Seem like the Job you've passed is null.

**Comment by channguyen** [comment]
We pass all our jobs as `jobManager.addJobInBackground(new AbcJob())` everywhere, so I can be sure that the job is not null at that time. 
However, there is only one place, we use cancel the job with TAG. I'm wondering that could potentially be the issue? The call to `cancelJobsInBackground` is inside a callback (Snackbar).

**Comment by franklinharper** [comment]
Yigit,

Chan and I work on the same app. Something else to consider is that all the crashes are happening on Android 4.x. None at all on Android 5, 6 or 7.

**Comment by yigit** [comment]
Hi,
Which version are you running? The lines do not match the source code in `JobManagerThread`.
If the lines in the Job are matching, looks like a tag is `null`:

```
if (readonlyTags != null) {
  for (String tag : readonlyTags) {
    if (tag.startsWith(SINGLE_ID_TAG_PREFIX)) {
      return tag;
    }
  }
}
```

Any chance you are adding a null tag to a job? We should still guard against it but that might be the bug.

**Comment by channguyen** [comment]
Hi there, 

Nice catch! I think we probably have use `null` tag when cancelling. We're using 2.0.0, will upgrade to 2.0.1. Thanks a lot for the help.

**Comment by yigit** [comment]
ok, i'll keep this report open to check for nulls in tags.
