### ISSUE TITLE
Fatal Exception: android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 

### ISSUE THREAD

**Issue by atulgoswami21** [yigit/android-priority-jobqueue#305]
here is the stack trace.

_

> Fatal Exception: android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
>        at android.database.CursorWindow.<init>(CursorWindow.java:104)
>        at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
>        at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
>        at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
>        at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
>        at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
>        at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.nextJobAndIncRunCount(SqliteJobQueue.java:297)
>        at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.nextJobAndIncRunCount(CachedJobQueue.java:79)
>        at com.birbit.android.jobqueue.JobManagerThread.getNextJob(JobManagerThread.java:665)
>        at com.birbit.android.jobqueue.JobManagerThread.getNextJob(JobManagerThread.java:642)
>        at com.birbit.android.jobqueue.ConsumerManager.handleIdle(ConsumerManager.java:199)
>        at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:231)
>        at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
>        at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:222)
>        at java.lang.Thread.run(Thread.java:841)

_

**Comment by yigit** [comment]
any steps to reproduce ?

**Comment by readmycodetanos** [comment]
using diffrent google version dependency . will cash this kind of issue
