### ISSUE TITLE
Cannot save job to disk

### ISSUE THREAD

**Issue by tapasya** [yigit/android-priority-jobqueue#306]
We have been lot of below crashes from users. 

java.lang.RuntimeException: cannot save job to disk
at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.persistJobToDisk(SourceFile:107)
at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.insert(SourceFile:90)
at com.birbit.android.jobqueue.a.a.insert(SourceFile:29)
at com.birbit.android.jobqueue.s.a(SourceFile:141)
at com.birbit.android.jobqueue.s.a(SourceFile:35)
at com.birbit.android.jobqueue.t.a(SourceFile:225)
at com.birbit.android.jobqueue.messaging.g.a(SourceFile:39)
at com.birbit.android.jobqueue.s.run(SourceFile:220)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.FileNotFoundException: /data/data/************/app_com_birbit_jobqueue_jobs/files_jobs_default_job_manager/8cebf320-07c4-44df-a89e-9d1d331d9e2f.jobs: open failed: ENOSPC (No space left on device)
at libcore.io.IoBridge.open(IoBridge.java:456)
at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
at okio.p.b(SourceFile:181)
at com.birbit.android.jobqueue.persistentQueue.sqlite.b.a(SourceFile:57)
at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.persistJobToDisk(SourceFile:105)
... 8 more
Caused by: android.system.ErrnoException: open failed: ENOSPC (No space left on device)
at libcore.io.Posix.open(Native Method)
at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
at libcore.io.IoBridge.open(IoBridge.java:442)
... 13 more

**Comment by yigit** [comment]
well as it say, no space left on device. Nothing much the library can do for this.

**Comment by tapasya** [comment]
Error Log :

Error Report collected on : Wed Feb 15 11:05:45 GMT+05:30 2017

Information :
Locale: en_GB
Version: V2.2.1
Package: com.kpt.xploree.app
Phone Model: SM-J200G
Android Version: 5.1.1
Board: universal3475
Brand: samsung
Device: j2lte
Host: SWHE2305
ID: LMY47X
Model: SM-J200G
Product: j2ltedd
Type: user
Total Internal memory: 4853288960
Available Internal memory: 1893801984
Stack:
java.lang.RuntimeException: cannot save job to disk
at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.persistJobToDisk(SourceFile:107)
at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.insert(SourceFile:90)
at com.birbit.android.jobqueue.a.a.insert(SourceFile:29)
at com.birbit.android.jobqueue.s.a(SourceFile:141)
at com.birbit.android.jobqueue.s.a(SourceFile:35)
at com.birbit.android.jobqueue.t.a(SourceFile:225)
at com.birbit.android.jobqueue.messaging.g.a(SourceFile:39)
at com.birbit.android.jobqueue.s.run(SourceFile:220)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.FileNotFoundException: /data/data/com.kpt.xploree.app/app_com_birbit_jobqueue_jobs/files_jobs_default_job_manager/9728940b-3ce1-4c9f-8192-9659b2334ff1.jobs: open failed: ENOSPC (No space left on device)
at libcore.io.IoBridge.open(IoBridge.java:456)
at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
at okio.p.b(SourceFile:181)
at com.birbit.android.jobqueue.persistentQueue.sqlite.b.a(SourceFile:57)
at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.persistJobToDisk(SourceFile:105)
... 8 more
Caused by: android.system.ErrnoException: open failed: ENOSPC (No space left on device)
at libcore.io.Posix.open(Native Method)
at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
at libcore.io.IoBridge.open(IoBridge.java:442)
... 13 more

**** End of current Report ***

**Comment by tapasya** [comment]
@yigit seems like internal memory is available but still the stack trace is showing no space. any comments ?

**Comment by rom4ek** [comment]
Faced with the same issue. @yigit maybe some way to handle it, or at least to notify user that there is no space left on the device? Crash for no reason seems a bit annoying for user :)
