### ISSUE TITLE
cannot save job to disk

### ISSUE THREAD

**Issue by jermainedilao** [yigit/android-priority-jobqueue#315]
Hi, just updraded from 1.3.5 to 2.0.1.

Why is it that when I inject an object to my Job i always get this. (in this case I injected an instance of Retrofit using Dagger 2) 

```
cannot save job to disk
                         E  java.lang.RuntimeException: cannot save job to disk
                         E      at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.persistJobToDisk(SqliteJobQueue.java:107)
                         E      at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.insertOrReplace(SqliteJobQueue.java:186)
                         E      at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.insertOrReplace(CachedJobQueue.java:39)
                         E      at com.birbit.android.jobqueue.JobManagerThread.reAddJob(JobManagerThread.java:550)
                         E      at com.birbit.android.jobqueue.JobManagerThread.insertOrReplace(JobManagerThread.java:531)
                         E      at com.birbit.android.jobqueue.JobManagerThread.handleRunJobResult(JobManagerThread.java:492)
                         E      at com.birbit.android.jobqueue.JobManagerThread.access$300(JobManagerThread.java:35)
                         E      at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:237)
                         E      at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
                         E      at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:222)
                         E      at java.lang.Thread.run(Thread.java:841)
                         E  Caused by: java.io.NotSerializableException: com.yyyjobs.android.App
                         E      at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1364)
                         E      at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1671)
                         E      at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517)
                         E      at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481)
                         E      at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:979)
                         E      at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:368)
                         E      at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1074)
                         E      at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1404)
                         E      at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1671)
                         E      at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1517)
                         E      at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1481)
                         E      at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue$JavaSerializer.serialize(SqliteJobQueue.java:493)
                         E      at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.persistJobToDisk(SqliteJobQueue.java:105)
                         E      ... 10 more


```

BTW. my job is persistent. It used to be no problem before i upgraded to the latest version. but now I get this error.

**Comment by jermainedilao** [comment]
My bad.. the reason was in my BaseJob i injected an Application context. changed it now using (getApplicationContext) and it now works.
