### ISSUE TITLE
Cannot save job to disk

### ISSUE THREAD

**Issue by hungdh0x5e** [yigit/android-priority-jobqueue#319]
Can you tell me how to fix it? I had check https://github.com/yigit/android-priority-jobqueue/issues/255 but it's not working for me.

**SignInJob**

```
private void signIn() {
  Configuration.Builder builder = new Configuration.Builder(this)
          .minConsumerCount(1)//always keep at least one consumer alive
          .maxConsumerCount(5)//up to 3 consumers at a time
          .loadFactor(3)//3 jobs per consumer
          .consumerKeepAlive(30);//wait 2 minute
  JobManager jobManager = new JobManager(builder.build());
  for (int i = 1; i < 2; i++) {
      Job job = new SmsJob(this, null, "016771xxxx", "this is content + " + i);
      jobManager.addJobInBackground(job);
  }
}
```

**SmsJob class**

```
public class SmsJob extends Job {
    public static final int PRIORITY = 1;
    private Context context;
    private Bundle header;
    private String destAddr;
    private String content;

    public SmsJob(Context context, Bundle header, String destAddr, String content) {
        super(new Params(PRIORITY).requireNetwork().persist());
        this.context = context;
        this.header = header;
        this.destAddr = destAddr;
        this.content = content;
    }
    @Override
    public void onAdded() {
    }
    @Override
    public void onRun() throws Throwable {
        AppFunction.sendSmsSingleDest(context, header, destAddr, content);
    }
    @Override
    protected RetryConstraint shouldReRunOnThrowable(Throwable throwable, int runCount,
                                                     int maxRunCount) {
        return RetryConstraint.createExponentialBackoff(runCount, 1000);
    }
    @Override
    protected void onCancel(@CancelReason int cancelReason, @Nullable Throwable throwable) {
    }
}
```

**Exception**

```
FATAL EXCEPTION: job-manager
  Process: com.wefit.sms, PID: 16473
  java.lang.RuntimeException: cannot save job to disk
  at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.persistJobToDisk(SqliteJobQueue.java:107)
  at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.insert(SqliteJobQueue.java:90)
  at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.insert(CachedJobQueue.java:29)
  at com.birbit.android.jobqueue.JobManagerThread.handleAddJob(JobManagerThread.java:143)
  at com.birbit.android.jobqueue.JobManagerThread.access$100(JobManagerThread.java:35)
  at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:228)
  at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
  at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:222)
  at java.lang.Thread.run(Thread.java:761)
      Caused by: java.io.NotSerializableException: com.wefit.sms.activity.SignInActivity
  at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1224)
  at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1584)
  at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1549)
  at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
  at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
  at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
  at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue$JavaSerializer.serialize(SqliteJobQueue.java:493)
  at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.persistJobToDisk(SqliteJobQueue.java:105)
```

**Comment by dsardari** [comment]
Bundle and Context aren't Serializable. Use [Job's getApplicationContext()](https://github.com/yigit/android-priority-jobqueue/blob/master/jobqueue/src/main/java/com/birbit/android/jobqueue/Job.java#L383) for your context and find a different way to pass in the bundle data.

**Comment by hungdh0x5e** [comment]
Thanks! It's work, have a nice day.
