### ISSUE TITLE
Fatal Exception: android.database.sqlite.SQLiteException

### ISSUE THREAD

**Issue by mayankkrjain** [yigit/android-priority-jobqueue#335]
We have been using this library in our SDK to track application events. One of our clients is facing this issue . There has been a spike in these crashes in last 90 days (~20 reported instances). We are unable to figure out the issue. Can you help us here. 
We are not using the persist option as you can see below. So even then **will** the database come into picture?
Another point  is that we are using 2.0.0-beta2 version of library. We have a restriction in our implementation because of which we are avoiding the persist call. Is updating to the latest version : 2.0.1 safe for us ?

`super(new` `Params(PRIORITY).requireNetwork());`
`Fatal Exception: android.database.sqlite.SQLiteException: not an error (code 0): Could not open the database in read/write mode.
       at android.database.sqlite.SQLiteConnection.nativeOpen(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:318)
       at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:228)
       at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:512)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
       at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:178)
       at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:908)
       at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:878)
       at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:699)
       at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:1339)
       at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:274)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
       at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.<init>(SqliteJobQueue.java:49)
       at com.birbit.android.jobqueue.DefaultQueueFactory.createPersistentQueue(DefaultQueueFactory.java:27)
       at com.birbit.android.jobqueue.JobManagerThread.<init>(JobManagerThread.java:85)
       at com.birbit.android.jobqueue.JobManager.<init>(JobManager.java:62)
`

**Comment by yigit** [comment]
JobManager will always open the database. If you don't need it, I recommend providing a QueueFactory that returns a dummy queue in the persistent callback option. Or you can just return another instance of the non-persistent queue.

**Comment by yigit** [comment]
And yes, you should update to 2.0.1
