### ISSUE TITLE
java.lang.IllegalArgumentException Error

### ISSUE THREAD

**Issue by MahdiPishguy** [yigit/android-priority-jobqueue#361]
when i'm trying to use `addJobInBackground` in my application job work after close and reopen application, and when i try to use that again i get this error:

```
java.lang.IllegalArgumentException: No such service ComponentInfo{com.kermany.behandam/com.kermany.behandam.Service.ApplicationJobService}
    at android.os.Parcel.readException(Parcel.java:1694)
    at android.os.Parcel.readException(Parcel.java:1640)
    at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:158)
    at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:42)
    at com.birbit.android.jobqueue.scheduling.FrameworkScheduler.request(FrameworkScheduler.java:120)
    at com.birbit.android.jobqueue.BatchingScheduler.request(BatchingScheduler.java:142)
    at com.birbit.android.jobqueue.JobManagerThread.scheduleWakeUpFor(JobManagerThread.java:192)
    at com.birbit.android.jobqueue.JobManagerThread.handleAddJob(JobManagerThread.java:163)
    at com.birbit.android.jobqueue.JobManagerThread.access$100(JobManagerThread.java:35)
    at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:228)
    at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
    at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:222)
    at java.lang.Thread.run(Thread.java:761)
```

`ApplicationJobService` class:

```
public class ApplicationJobService extends FrameworkJobSchedulerService {
    @Inject
    JobManager jobManager;

    @NonNull
    @Override
    protected JobManager getJobManager() {
        return jobManager;
    }
}
```

**Comment by gouravd** [comment]
@MahdiPishguy how was this resolved?

**Comment by Mrp12** [comment]
@MahdiPishguy i forget that

**Comment by MahdiPishguy** [comment]
@gouravd  i forget that
