### ISSUE TITLE
Null Pointer Power Manager

### ISSUE THREAD

**Issue by moonlightbrandon** [yigit/android-priority-jobqueue#363]
Getting a crash report from our Firebase, any ideas?

Exception java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.os.IPowerManager.isDeviceIdleMode()' on a null object reference

```
android.os.PowerManager.isDeviceIdleMode (PowerManager.java:995)
com.birbit.android.jobqueue.network.NetworkUtilImpl.isDozing ()
com.birbit.android.jobqueue.network.NetworkUtilImpl.getNetworkStatus ()
com.birbit.android.jobqueue.JobManagerThread.getNetworkStatus ()
com.birbit.android.jobqueue.JobManagerThread.a ()
com.birbit.android.jobqueue.JobManagerThread$1.onIdle ()
com.birbit.android.jobqueue.messaging.PriorityMessageQueue.next ()
com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume ()
com.birbit.android.jobqueue.JobManagerThread.run ()
java.lang.Thread.run (Thread.java:818)
```

**Comment by yigit** [comment]
Hmm wonder why power manager is returning null. We can just null check it.
Do you have any repro steps or device details?

**Comment by moonlightbrandon** [comment]
There are no reproduction steps.  This was an error report from Firebase, and it did not have a stack trace either.

Manufacturer: LGE
Model: LG-H740
Board: Msm8952
Android API: 23
Android OS: 6.0.1
Brand: Lge
RAM: 1.84GB
Orientation: Portrait

I know it is not much, but I just wanted to make you aware.  It only affected one user out of the tens of thousands we have on our platform.  Thanks again for jobqueue, made our lives a lot easier.

**Comment by robmarinaro** [comment]
I am seeing the same issue reported by firebase as well.

`Fatal Exception: java.lang.NullPointerException
       at android.os.PowerManager.isDeviceIdleMode(PowerManager.java:1055)
       at com.birbit.android.jobqueue.network.NetworkUtilImpl.isDozing(NetworkUtilImpl.java:109)
       at com.birbit.android.jobqueue.network.NetworkUtilImpl.getNetworkStatus(NetworkUtilImpl.java:77)
       at com.birbit.android.jobqueue.JobManagerThread.getNetworkStatus(JobManagerThread.java:599)
       at com.birbit.android.jobqueue.JobManagerThread.getNextWakeUpNs(JobManagerThread.java:604)
       at com.birbit.android.jobqueue.JobManagerThread$1.onIdle(JobManagerThread.java:272)
       at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.next(PriorityMessageQueue.java:89)
       at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:36)
       at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:222)
       at java.lang.Thread.run(Thread.java:748)`
