### ISSUE TITLE
java.lang.RuntimeException: cannot save job to disk   AND  Caused by: java.io.NotSerializableException: org.json.JSONObject

### ISSUE THREAD

**Issue by onkarshelke** [yigit/android-priority-jobqueue#364]
java.lang.RuntimeException: cannot save job to disk
	at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.persistJobToDisk(SqliteJobQueue.java:107)
	at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.insert(SqliteJobQueue.java:90)
	at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.insert(CachedJobQueue.java:29)
	at com.birbit.android.jobqueue.JobManagerThread.handleAddJob(JobManagerThread.java:143)
	at com.birbit.android.jobqueue.JobManagerThread.access$100(JobManagerThread.java:35)
	at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:228)
	at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
	at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:222)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.NotSerializableException: org.json.JSONObject
	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
	at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
	at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
	at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
	at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
	at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
	at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue$JavaSerializer.serialize(SqliteJobQueue.java:493)
	at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.persistJobToDisk(SqliteJobQueue.java:105)
	... 8 more

**Comment by onkarshelke** [comment]
@yigit can you please help me with this ?

**Comment by yigit** [comment]
the exception is clear, you have a org.json.JSONObject in your Job but it is not serializable. You can either provide a custom serializer (via the configuration) that supports serializing this object for use another object type to hold that data that is serializable.

**Comment by onkarshelke** [comment]
@yigit Thanks alot you solved my bug.
