### ISSUE TITLE
Database exception

### ISSUE THREAD

**Issue by debjitk** [yigit/android-priority-jobqueue#369]
I am enqueuing a lot of jobs sometimes upto 10000. I am having two issues primarily ....

1. Sometimes all the jobs does not get completed.
2. The app hangs sometimes.
3. I am getting the following exception
    E/AndroidRuntime: FATAL EXCEPTION: job-manager
                                                                  Process: com.pixo.android, PID: 16419
                                                                  android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)

**Comment by gotama** [comment]
Hi,

Im getting the code 14 issue as well under high stress.  the Job Queue just cant handle big loads.

`Fatal Exception: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
       at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
       at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
       at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
       at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.nextJobAndIncRunCount(SqliteJobQueue.java:297)
       at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.nextJobAndIncRunCount(CachedJobQueue.java:79)
       at com.birbit.android.jobqueue.JobManagerThread.getNextJob(JobManagerThread.java:665)
       at com.birbit.android.jobqueue.JobManagerThread.getNextJob(JobManagerThread.java:642)
       at com.birbit.android.jobqueue.ConsumerManager.handleIdle(ConsumerManager.java:199)
       at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:231)
       at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
       at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:222)
       at java.lang.Thread.run(Thread.java:841)`

**Comment by shawnlinboy** [comment]
I've got this same issue while running [MONKEY test](https://developer.android.com/studio/test/monkey.html) on my app, this may also be described as `under high payload` like your title given above, and here is my issue: https://github.com/yigit/android-priority-jobqueue/issues/407
