### ISSUE TITLE
master branch fails to build

### ISSUE THREAD

**Issue by kherink** [yigit/android-priority-jobqueue#37]
I am unable to build the code using the steps outlined here: https://github.com/yigit/android-priority-jobqueue#building

i did: 
$ git clone https://github.com/yigit/android-priority-jobqueue.git
$ cd android-priority-jobqueue/jobqueue
$ ./gradlew clean assembleDebug assembleDebugUnitTest test

Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.IllegalArgumentException: android.compileSdkVersion is missing!
	at com.android.build.gradle.internal.SdkHandler.initTarget(SdkHandler.java:80)
	at com.android.build.gradle.BasePlugin.ensureTargetSetup(BasePlugin.groovy:467)
	at com.android.build.gradle.BasePlugin.access$0(BasePlugin.groovy)
	at com.android.build.gradle.BasePlugin$_createTasks_closure9.doCall(BasePlugin.groovy:372)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:278)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
	at groovy.lang.Closure.call(Closure.java:423)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy13.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:79)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:65)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:504)
	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:83)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:42)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:129)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/kaja/paloma/android-priority-jobqueue/jobqueue/build.gradle' line: 6

* What went wrong:
A problem occurred evaluating root project 'jobqueue'.
> /Users/kaja/paloma/android-priority-jobqueue/jobqueue/releaseConfig.properties (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.551 secs

**Comment by kherink** [comment]
I've managed to get the build going by adding a `releaseConfig.properties` file with the following contents:

`
releaseConfig.ossrhUsername=unset
releaseConfig.ossrhPassword=unset
`

however 12 tests (all in `com.path.android.jobqueue.test.jobmanager.RetryLogicTest`) fail

**Comment by yigit** [comment]
What is the failure you are seeing ?

**Comment by kherink** [comment]
karel-herinks-MacBook-Pro:jobqueue kaja$ ./gradlew clean assembleDebug assembleDebugUnitTest test
version name:1.3.3
checking variant debug
checking variant release
found release variant
ossr username: null
:clean
:compileLint
:copyDebugLint UP-TO-DATE
:mergeDebugProguardFiles UP-TO-DATE
:preBuild UP-TO-DATE
:preDebugBuild UP-TO-DATE
:checkDebugManifest
:prepareDebugDependencies
:compileDebugAidl
:compileDebugRenderscript
:generateDebugBuildConfig
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues UP-TO-DATE
:generateDebugResources
:packageDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:compileDebugJava
Note: /Users/kaja/paloma/android-priority-jobqueue/jobqueue/src/main/java/com/path/android/jobqueue/persistentQueue/sqlite/SqliteJobQueue.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:unzipJacocoAgent
:instrumentDebug
:processDebugJavaRes UP-TO-DATE
:packageDebugJar
:compileDebugNdk UP-TO-DATE
:packageDebugJniLibs UP-TO-DATE
:packageDebugLocalJar
:packageDebugRenderscript UP-TO-DATE
:bundleDebug
:assembleDebug
:preCompileDebugUnitTestJava
:compileDebugUnitTestJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/kaja/paloma/android-priority-jobqueue/jobqueue/src/test/java/com/path/android/jobqueue/test/jobqueue/JobQueueTestBase.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:compileDebugUnitTestSources
:mockableAndroidJar
:assembleDebugUnitTest
:testDebug
objc[66042]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.7.0_76.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.7.0_76.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.

com.path.android.jobqueue.test.jobmanager.RetryLogicTest > retryPersistent FAILED
    java.lang.AssertionError at RetryLogicTest.java:290

com.path.android.jobqueue.test.jobmanager.RetryLogicTest > testRunCountPersistent FAILED
    java.lang.AssertionError at RetryLogicTest.java:91

com.path.android.jobqueue.test.jobmanager.RetryLogicTest > testCancelPersistent FAILED
    java.lang.AssertionError at RetryLogicTest.java:254

com.path.android.jobqueue.test.jobmanager.RetryLogicTest > testCancelNonPersistent FAILED
    java.lang.AssertionError at RetryLogicTest.java:254

com.path.android.jobqueue.test.jobmanager.RetryLogicTest > testChangeDelayNonPersistent FAILED
    java.lang.AssertionError at RetryLogicTest.java:129

com.path.android.jobqueue.test.jobmanager.RetryLogicTest > retryNonPersistent FAILED
    java.lang.AssertionError at RetryLogicTest.java:290

com.path.android.jobqueue.test.jobmanager.RetryLogicTest > testRunCountNonPersistent FAILED
    java.lang.AssertionError at RetryLogicTest.java:91

com.path.android.jobqueue.test.jobmanager.RetryLogicTest > testChangePriorityAndObserveExecutionOrderPersistent FAILED
    java.lang.AssertionError at RetryLogicTest.java:183

com.path.android.jobqueue.test.jobmanager.RetryLogicTest > testChangePriorityAndObserveExecutionOrderNonPersistent FAILED
    java.lang.AssertionError at RetryLogicTest.java:183

com.path.android.jobqueue.test.jobmanager.RetryLogicTest > retryPersistentWithNull FAILED
    java.lang.AssertionError at RetryLogicTest.java:290

com.path.android.jobqueue.test.jobmanager.RetryLogicTest > testChangeDelayPersistent FAILED
    java.lang.AssertionError at RetryLogicTest.java:129

com.path.android.jobqueue.test.jobmanager.RetryLogicTest > retryNonPersistentWithNull FAILED
    java.lang.AssertionError at RetryLogicTest.java:290

139 tests completed, 12 failed
:testDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':testDebug'.
> There were failing tests. See the report at: file:///Users/kaja/paloma/android-priority-jobqueue/jobqueue/build/reports/tests/debug/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3 mins 21.996 secs
karel-herinks-MacBook-Pro:jobqueue kaja$

**Comment by yigit** [comment]
hmm it is failing to create the database :/. I'll check whats going on, might be sth related to robolectric usage. Thanks for the logs.

**Comment by yigit** [comment]
I did a revamp on this. Can you please try current master branch?
FYI, you can run `./gradlew clean check` to run tests.

**Comment by kherink** [comment]
now all the tests fail with:
java.lang.UnsupportedOperationException: Robolectric does not support API level 23.
	at org.robolectric.internal.SdkConfig.<init>(SdkConfig.java:42)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:187)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:86)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:49)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:69)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by yigit** [comment]
sorry forgot the roboelectric props file :/. should be good now, can you try again?

**Comment by kherink** [comment]
after receiving the robolectric.properties we're all good:
BUILD SUCCESSFUL
Total time: 5 mins 11.813 secs
:)

**Comment by yigit** [comment]
great, thanks for the verification.
