### ISSUE TITLE
database is locked (code 5)

### ISSUE THREAD

**Issue by rasoulinejad** [yigit/android-priority-jobqueue#373]
This error occurred on device like samsung SM-J200H , HUAWEI G610-U20, LENOVO , ...

android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
	at android.database.sqlite.SQLiteConnection.nativeExecute(SQLiteConnection.java)
	at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:552)
	at android.database.sqlite.SQLiteSession.beginTransactionUnchecked(SQLiteSession.java:323)
	at android.database.sqlite.SQLiteSession.beginTransaction(SQLiteSession.java:298)
	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:505)
	at android.database.sqlite.SQLiteDatabase.beginTransaction(SQLiteDatabase.java:416)
	at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.delete(SqliteJobQueue.java:205)
	at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.remove(SqliteJobQueue.java:201)
	at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.remove(CachedJobQueue.java:51)
	at com.birbit.android.jobqueue.JobManagerThread.removeJob(JobManagerThread.java:561)
	at com.birbit.android.jobqueue.JobManagerThread.handleRunJobResult(JobManagerThread.java:472)
	at com.birbit.android.jobqueue.JobManagerThread.access$300(JobManagerThread.java:35)
	at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:237)
	at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
	at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:222)
	at java.lang.Thread.run(Thread.java:838)

**Comment by Githeo** [comment]
Exactly the same problem here.

![image](https://user-images.githubusercontent.com/8645265/31888904-1e1c8334-b7fe-11e7-846d-9db9723b6269.png)

**Comment by nischayn22** [comment]
This still happens on Lenovo. Any workaround suggestions?

**Comment by jandoblelim** [comment]
Still getting this too...hmm

**Comment by toantran-ea** [comment]
I'm having this exactly issue on Fabric :| seems like this library has not been really active for a long time, going to remove this libs  😢

**Comment by jandoblelim** [comment]
@toantran-ea Time to start using the WorkManager 👯
