### ISSUE TITLE
Jobqueue: CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 

### ISSUE THREAD

**Issue by balrampandey19** [yigit/android-priority-jobqueue#377]
I have the latest version of jobqueue  and I received many crashes  "CursorWindowAllocationException"

'''

Fatal Exception: android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. 
       at android.database.CursorWindow.<init>(CursorWindow.java:108)
       at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
       at android.database.AbstractCursor.moveToNext(AbstractCursor.java:268)
       at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.nextJobAndIncRunCount(SqliteJobQueue.java:297)
       at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.nextJobAndIncRunCount(CachedJobQueue.java:79)
       at com.birbit.android.jobqueue.JobManagerThread.getNextJob(JobManagerThread.java:665)
       at com.birbit.android.jobqueue.JobManagerThread.getNextJob(JobManagerThread.java:642)
       at com.birbit.android.jobqueue.ConsumerManager.handleIdle(ConsumerManager.java:199)
       at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:231)
       at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
       at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:222)
       at java.lang.Thread.run(Thread.java:818)

'''

**Comment by gotama** [comment]
Getting this issue as well 
`Fatal Exception: android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=1 (# cursors opened by this proc=1)
       at android.database.CursorWindow.<init>(CursorWindow.java:108)
       at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
       at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.loadTags(SqliteJobQueue.java:448)
       at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.createJobHolderFromCursor(SqliteJobQueue.java:424)
       at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.nextJobAndIncRunCount(SqliteJobQueue.java:300)
       at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.nextJobAndIncRunCount(CachedJobQueue.java:79)
       at com.birbit.android.jobqueue.JobManagerThread.getNextJob(JobManagerThread.java:652)
       at com.birbit.android.jobqueue.JobManagerThread.getNextJob(JobManagerThread.java:629)
       at com.birbit.android.jobqueue.ConsumerManager.handleIdle(ConsumerManager.java:190)
       at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:228)
       at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
       at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:220)
       at java.lang.Thread.run(Thread.java:818)`
