### ISSUE TITLE
 cannot save job to disk

### ISSUE THREAD

**Issue by rasoulinejad** [yigit/android-priority-jobqueue#383]
Android: 4.0.4
Manufacturer: samsung
Model: GT-S5301
Thread: job-manager-11123

java.lang.RuntimeException: cannot save job to disk	at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.persistJobToDisk(SqliteJobQueue.java:107)
	at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.insert(SqliteJobQueue.java:90)
	at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.insert(CachedJobQueue.java:29)
	at com.birbit.android.jobqueue.JobManagerThread.handleAddJob(JobManagerThread.java:143)
	at com.birbit.android.jobqueue.JobManagerThread.access$100(JobManagerThread.java:35)
	at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:228)
	at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
	at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:222)
	at java.lang.Thread.run(Thread.java:856)
Caused by: java.io.FileNotFoundException: /data/data/com.gapafzar.messenger/app_com_birbit_jobqueue_jobs/files_jobs_3/0185c423-67af-443e-a133-591f78264c86.jobs: open failed: EMFILE (Too many open files)
	at libcore.io.IoBridge.open(IoBridge.java:406)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:88)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:73)
	at okio.Okio.sink(Okio.java:179)
	at com.birbit.android.jobqueue.persistentQueue.sqlite.FileStorage.save(FileStorage.java:57) at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.persistJobToDisk(SqliteJobQueue.java:105)
	... 8 more
Caused by: libcore.io.ErrnoException: open failed: EMFILE (Too many open files)
	at libcore.io.Posix.open(Posix.java)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
	at libcore.io.IoBridge.open(IoBridge.java:390)
	... 13 more

**Comment by crossle** [comment]
same problem
