### ISSUE TITLE
Fatal Exception: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)

### ISSUE THREAD

**Issue by TasneemBohra** [yigit/android-priority-jobqueue#391]
`Fatal Exception: android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
       at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(SQLiteConnection.java)
       at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
       at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
       at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
       at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.loadTags(SqliteJobQueue.java:448)
       at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.createJobHolderFromCursor(SqliteJobQueue.java:424)
       at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.nextJobAndIncRunCount(SqliteJobQueue.java:300)
       at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.nextJobAndIncRunCount(CachedJobQueue.java:79)
       at com.birbit.android.jobqueue.JobManagerThread.getNextJob(JobManagerThread.java:665)
       at com.birbit.android.jobqueue.JobManagerThread.getNextJob(JobManagerThread.java:642)
       at com.birbit.android.jobqueue.ConsumerManager.handleIdle(ConsumerManager.java:199)
       at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:231)
       at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
       at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:222)
       at java.lang.Thread.run(Thread.java:761)`

**Comment by GabrielJanucik** [comment]
@yigit any feedback here? I encountered the same problem.
