### ISSUE TITLE
android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)

### ISSUE THREAD

**Issue by shawnlinboy** [yigit/android-priority-jobqueue#407]
I got the following error while running Monkey test on my app:

```
09-29 00:52:08.780 E/SQLiteQuery(28835): exception: unable to open database file (code 14); query: SELECT * FROM job_holder WHERE ( (deadline != 9223372036854775807 AND deadline <= ?) OR network_type <= ?) AND (cancelled IS NULL OR cancelled != 1) AND delay_until_ns <= ? AND running_session_id != ? ORDER BY priority DESC,created_ns ASC,insertionOrder ASC LIMIT 1

// android.database.sqlite.SQLiteCantOpenDatabaseException: unable to open database file (code 14)
// 	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
// 	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:853)
// 	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
// 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
// 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:151)
// 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
// 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
// 	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:268)
// 	at com.birbit.android.jobqueue.persistentQueue.sqlite.c.b(SourceFile:297)
// 	at com.birbit.android.jobqueue.a.a.b(SourceFile:79)
// 	at com.birbit.android.jobqueue.n.a(SourceFile:665)
// 	at com.birbit.android.jobqueue.n.b(SourceFile:642)
// 	at com.birbit.android.jobqueue.i.a(SourceFile:199)
// 	at com.birbit.android.jobqueue.n$1.a(SourceFile:231)
// 	at com.birbit.android.jobqueue.messaging.g.a(SourceFile:39)
// 	at com.birbit.android.jobqueue.n.run(SourceFile:222)
// 	at java.lang.Thread.run(Thread.java:761)
```
I've looked up all related issues but did not find any useful solution. Can we upload a patchset to catch this exception?

**Comment by yigit** [comment]
make sure you remove the job queue tables from backup and restore.

**Comment by shawnlinboy** [comment]
@yigit I'm afraid I didn't manipulate db file by myself, actually all  db accesses should be transparent to developers according to `android-priority-jobqueue`'s architecture design, which means developers should not manipulate any `db_XXXX.db` file  created by `android-priority-jobqueue` right? How can this exception happened there, it's really weird.
