### ISSUE TITLE
A required meta-data tag in your app's AndroidManifest.xml does not exist

### ISSUE THREAD

**Issue by marlene89** [yigit/android-priority-jobqueue#410]
I am running into an issue after integration your library. I added the job manager configuration to my application class, but its failing unit tests with this error:

**java.lang.IllegalStateException: A required meta-data tag in your app's AndroidManifest.xml does not exist.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
	at com.google.android.gms.common.zzo.isGooglePlayServicesAvailable(Unknown Source)
	at com.google.android.gms.common.zzo.isGooglePlayServicesAvailable(Unknown Source)
	at com.google.android.gms.common.zze.isGooglePlayServicesAvailable(Unknown Source)
	at com.google.android.gms.common.zze.isGooglePlayServicesAvailable(Unknown Source)
	at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source)
	at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source)
	at com.example.myapp.AppClass.configureJobManager(AppClass.java:172)
	at com.example.myapp.AppClass.onCreate(AppClass.java:44)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:131)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:431)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:224)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:168)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)**

I know the issue is not related to your library, but I was wondering if anyone has come across the same issue. The error points to this line in the AppClass
```java
int enableGcm = GoogleApiAvailability.getInstance().isGooglePlayServicesAvailable(this);
```
in this code snippet where I configure JobManager
```java
private void configureJobManager() {
        Configuration.Builder builder = new Configuration.Builder(this)
                .customLogger(new CustomLogger() {
                    private static final String TAG = "JOBS";
                    @Override
                    public boolean isDebugEnabled() {
                        return true;
                    }

                    @Override
                    public void d(String text, Object... args) {
                        Log.d(TAG, String.format(text, args));
                    }

                    @Override
                    public void e(Throwable t, String text, Object... args) {
                        Log.e(TAG, String.format(text, args), t);
                    }

                    @Override
                    public void e(String text, Object... args) {
                        Log.e(TAG, String.format(text, args));
                    }

                    @Override
                    public void v(String text, Object... args) {

                    }
                })
                .minConsumerCount(1)//always keep at least one consumer alive
                .maxConsumerCount(3)//up to 3 consumers at a time
                .loadFactor(3)//3 jobs per consumer
                .consumerKeepAlive(120)//wait 2 minute
                .injector(new DependencyInjector() {
                    @Override
                    public void inject(Job job) {
                        if (job instanceof DeleteSmsJob) {
                            ((DeleteSmsJob) job).spiceManager = new SpiceManager(ApiService.class);
                        }
                    }
                });
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            builder.scheduler(FrameworkJobSchedulerService.createSchedulerFor(this,
                    MyJobService.class), true);
        } else {
            int enableGcm = GoogleApiAvailability.getInstance().isGooglePlayServicesAvailable(this);
            if (enableGcm == ConnectionResult.SUCCESS) {
                builder.scheduler(GcmJobSchedulerService.createSchedulerFor(this,
                        MyGcmJobService.class), true);
            }
        }
        jobManager = new JobManager(builder.build());
    }
```

I added the missing meta-data tag in my manifest but I'm still seeing the same issue. Everything works fine when i install the app on a phone, its just failing the unit test. Any insights would be much appreciated. Thank you.

**Comment by jshvarts** [comment]
Does your AndroidManifest.xml contain something like this (with diff packages, of course):

```
<service android:name=".domain.services.jobs.SchedulerJobService"
            android:permission="android.permission.BIND_JOB_SERVICE" />

        <service
            android:name=".domain.services.jobs.GcmJobService"
            android:exported="true"
            android:permission="com.google.android.gms.permission.BIND_NETWORK_TASK_SERVICE">
            <intent-filter>
                <action android:name="com.google.android.gms.gcm.ACTION_TASK_READY" />
            </intent-filter>
        </service>
```

**Comment by marlene89** [comment]
I had the SchedulerJobService declaration in the manifest but I didnt have the GcmJobService declaration. But even after adding it, still seeing the same issue. works fine when i install on phone, but still failing tests with same error.
