### ISSUE TITLE
Getting error if I make job as persistent

### ISSUE THREAD

**Issue by TakeoffAndroid** [yigit/android-priority-jobqueue#412]
As it says, I have added even the BOOT_COMPLETED permission in manifest

```
10-25 14:12:40.158 4736-4761/com.learn2crack.filedownload E/AndroidRuntime: FATAL EXCEPTION: job-manager
                                                                            Process: com.learn2crack.filedownload, PID: 4736
                                                                            java.lang.IllegalArgumentException: Error: requested job be persisted without holding RECEIVE_BOOT_COMPLETED permission.
                                                                                at android.os.Parcel.readException(Parcel.java:1624)
                                                                                at android.os.Parcel.readException(Parcel.java:1573)
                                                                                at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:121)
                                                                                at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:42)
                                                                                at com.birbit.android.jobqueue.scheduling.FrameworkScheduler.request(FrameworkScheduler.java:120)
                                                                                at com.birbit.android.jobqueue.BatchingScheduler.request(BatchingScheduler.java:142)
                                                                                at com.birbit.android.jobqueue.JobManagerThread.scheduleWakeUpFor(JobManagerThread.java:192)
                                                                                at com.birbit.android.jobqueue.JobManagerThread.handleAddJob(JobManagerThread.java:163)
                                                                                at com.birbit.android.jobqueue.JobManagerThread.access$100(JobManagerThread.java:35)
                                                                                at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:228)
                                                                                at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
                                                                                at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:222)
                                                                                at java.lang.Thread.run(Thread.java:818)

```

**Comment by TakeoffAndroid** [comment]
Closing this issue. The app should be uninstalled after providing permission.
