### ISSUE TITLE
IllegalArgumentException - Where is the problem? 

### ISSUE THREAD

**Issue by vs011** [yigit/android-priority-jobqueue#425]
java.lang.IllegalArgumentException: Too many NetworkRequests filed
                                                                         at android.os.Parcel.readException(Parcel.java:1946)
                                                                         at android.os.Parcel.readException(Parcel.java:1888)
                                                                         at android.net.IConnectivityManager$Stub$Proxy.listenForNetwork(IConnectivityManager.java:2401)
                                                                         at android.net.ConnectivityManager.sendRequestForNetwork(ConnectivityManager.java:2871)
                                                                         at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:3184)
                                                                         at android.net.ConnectivityManager.registerNetworkCallback(ConnectivityManager.java:3166)
                                                                         at com.birbit.android.jobqueue.network.NetworkUtilImpl.listenNetworkViaConnectivityManager(NetworkUtilImpl.java:47)
                                                                         at com.birbit.android.jobqueue.network.NetworkUtilImpl.<init>(NetworkUtilImpl.java:28)
                                                                         at com.birbit.android.jobqueue.config.Configuration$Builder.build(Configuration.java:462)
                                                                         at com.domainxxxx.appxxxx.utils.JobHelper.getConfiguration(JobHelper.java:38)
                                                                         at com.domainxxxx.appxxxx.fragments.WarenkorbFragment.onCreateView(WarenkorbFragment.java:165)

**Comment by Tougee** [comment]
[You can try this](https://github.com/yigit/android-priority-jobqueue/issues/404)
