### ISSUE TITLE
DeadSystemException on android 7

### ISSUE THREAD

**Issue by rasoulinejad** [yigit/android-priority-jobqueue#427]
java.lang.RuntimeException: android.os.DeadSystemException
at android.os.PowerManager.isDeviceIdleMode(PowerManager.java:1224)
at com.birbit.android.jobqueue.network.NetworkUtilImpl.isDozing(NetworkUtilImpl.java:109)
at com.birbit.android.jobqueue.network.NetworkUtilImpl.getNetworkStatus(NetworkUtilImpl.java:77)
at com.birbit.android.jobqueue.JobManagerThread.getNetworkStatus(JobManagerThread.java:599)
at com.birbit.android.jobqueue.JobManagerThread.getNextWakeUpNs(JobManagerThread.java:604)
at com.birbit.android.jobqueue.JobManagerThread$1.onIdle(JobManagerThread.java:272)
at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.next(PriorityMessageQueue.java:89)
at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:36)
	at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:222)

**Comment by mrpinott** [comment]
I experienced the same issue. Seems to happen on low battery and/or low resources with an idle back grounded application.

StackTrace:

Error Messagejava.lang.RuntimeException: android.os.DeadSystemExceptionWhereNetworkUtilImpl.java:33
Short Stacktrace0java.lang.RuntimeException: android.os.DeadSystemException1at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:956)2at com.path.android.jobqueue.network.NetworkUtilImpl.isConnected(NetworkUtilImpl.java:33)3at com.path.android.jobqueue.JobManager.hasNetwork(JobManager.java:258)4at com.path.android.jobqueue.JobManager.access$800(JobManager.java:25)5at com.path.android.jobqueue.JobManager$2.countRemainingReadyJobs(JobManager.java:467)6at com.path.android.jobqueue.executor.JobConsumerExecutor.isAboveLoadFactor(JobConsumerExecutor.java:100)7at com.path.android.jobqueue.executor.JobConsumerExecutor.doINeedANewThread(JobConsumerExecutor.java:63)8at com.path.android.jobqueue.executor.JobConsumerExecutor.canIDie(JobConsumerExecutor.java:47)9at com.path.android.jobqueue.executor.JobConsumerExecutor.access$300(JobConsumerExecutor.java:17)10at com.path.android.jobqueue.executor.JobConsumerExecutor$JobConsumer.run(JobConsumerExecutor.java:211)11at java.lang.Thread.run(Thread.java:764)12Caused by: android.os.DeadSystemException13... 11 more | 0 | java.lang.RuntimeException: android.os.DeadSystemException | 1 | at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:956) | 2 | at com.path.android.jobqueue.network.NetworkUtilImpl.isConnected(NetworkUtilImpl.java:33) | 3 | at com.path.android.jobqueue.JobManager.hasNetwork(JobManager.java:258) | 4 | at com.path.android.jobqueue.JobManager.access$800(JobManager.java:25) | 5 | at com.path.android.jobqueue.JobManager$2.countRemainingReadyJobs(JobManager.java:467) | 6 | at com.path.android.jobqueue.executor.JobConsumerExecutor.isAboveLoadFactor(JobConsumerExecutor.java:100) | 7 | at com.path.android.jobqueue.executor.JobConsumerExecutor.doINeedANewThread(JobConsumerExecutor.java:63) | 8 | at com.path.android.jobqueue.executor.JobConsumerExecutor.canIDie(JobConsumerExecutor.java:47) | 9 | at com.path.android.jobqueue.executor.JobConsumerExecutor.access$300(JobConsumerExecutor.java:17) | 10 | at com.path.android.jobqueue.executor.JobConsumerExecutor$JobConsumer.run(JobConsumerExecutor.java:211) | 11 | at java.lang.Thread.run(Thread.java:764) | 12 | Caused by: android.os.DeadSystemException | 13 | ... 11 more
0 | java.lang.RuntimeException: android.os.DeadSystemException
1 | at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:956)
2 | at com.path.android.jobqueue.network.NetworkUtilImpl.isConnected(NetworkUtilImpl.java:33)
3 | at com.path.android.jobqueue.JobManager.hasNetwork(JobManager.java:258)
4 | at com.path.android.jobqueue.JobManager.access$800(JobManager.java:25)
5 | at com.path.android.jobqueue.JobManager$2.countRemainingReadyJobs(JobManager.java:467)
6 | at com.path.android.jobqueue.executor.JobConsumerExecutor.isAboveLoadFactor(JobConsumerExecutor.java:100)
7 | at com.path.android.jobqueue.executor.JobConsumerExecutor.doINeedANewThread(JobConsumerExecutor.java:63)
8 | at com.path.android.jobqueue.executor.JobConsumerExecutor.canIDie(JobConsumerExecutor.java:47)
9 | at com.path.android.jobqueue.executor.JobConsumerExecutor.access$300(JobConsumerExecutor.java:17)
10 | at com.path.android.jobqueue.executor.JobConsumerExecutor$JobConsumer.run(JobConsumerExecutor.java:211)
11 | at java.lang.Thread.run(Thread.java:764)
12 | Caused by: android.os.DeadSystemException
13 | ... 11 more
