### ISSUE TITLE
SQLiteReadOnlyDatabaseException

### ISSUE THREAD

**Issue by zasunkx** [yigit/android-priority-jobqueue#44]
Hi, I get this error when trying to add a new Job:
Is this a Bug or am I doing something wrong?

-09 19:21:50.710  28332-30164/com.mypackage E/SQLiteLog﹕ (1032) statement aborts at 20: [INSERT INTO job_holder VALUES (?,?,?,?,?,?,?,?,?)]
10-09 19:21:50.710  28332-30164/com.mypackage E/SQLiteDBG﹕ func: executeNonQuery, errno: 2, error msg: No such file or directory, path: /data/data/com.mypackage/databases/db_default_job_manager, handle: 0xb8173718
10-09 19:21:50.710  28332-30164/com.mypackage E/JOBS﹕ addJobInBackground received an exception. job class: SendMsgJob
    android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
            at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
            at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:812)
            at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
            at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
            at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.insertWithTags(SqliteJobQueue.java:85)
            at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.insert(SqliteJobQueue.java:63)
            at com.path.android.jobqueue.cachedQueue.CachedJobQueue.insert(CachedJobQueue.java:28)
            at com.path.android.jobqueue.JobManager.addJob(JobManager.java:165)
            at com.path.android.jobqueue.JobManager$3.run(JobManager.java:396)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by yigit** [comment]
Thats weird, looks like it does not have write access to the database :/. Can you try on a different phone/emulator to see whats going on?
Also, maybe you are trying to put the database in a folder where you don't have write access?

**Comment by zasunkx** [comment]
Unfortunately it happens across all devices, but not regularly. It does work occasionally after a reinstall, extremely strange. Permissions shouldnt be a problem. 
The only things which could possibly be special about my use case is that I compile on API 23 and I have my own SQLite which is being accessed during onRun of my job. Ill see if one of those two things are the cause for my error.

**Comment by yigit** [comment]
what do you mean you have your own sqlite? Unless you are using the same sqlite file name, it should not be an issue.
