### ISSUE TITLE
Database problems

### ISSUE THREAD

**Issue by pavlejoksovicesteh** [yigit/android-priority-jobqueue#442]
I found the following error on crashlytics:

`Fatal Exception: android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=1 (# cursors opened by this proc=1)
       at android.database.CursorWindow.<init>(CursorWindow.java:108)
       at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
       at android.database.sqlite.SQLiteCursor.clearOrCreateWindow(SQLiteCursor.java:300)
       at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:138)
       at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
       at android.database.AbstractCursor.moveToNext(AbstractCursor.java:268)
       at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.nextJobAndIncRunCount(SqliteJobQueue.java:297)
       at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.nextJobAndIncRunCount(CachedJobQueue.java:79)
       at com.birbit.android.jobqueue.JobManagerThread.getNextJob(JobManagerThread.java:665)
       at com.birbit.android.jobqueue.JobManagerThread.getNextJob(JobManagerThread.java:642)
       at com.birbit.android.jobqueue.ConsumerManager.handleIdle(ConsumerManager.java:199)
       at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:231)
       at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
       at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:222)
       at java.lang.Thread.run(Thread.java:762)`

**Comment by dcboy** [comment]
how do fixed that?
