### ISSUE TITLE
Caused by: com.android.dex.DexException: Multiple dex files define 

### ISSUE THREAD

**Issue by KomoriWu** [yigit/android-priority-jobqueue#452]
Caused by: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/view/ViewPropertyAnimatorListener;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
	... 47 more

**Comment by KomoriWu** [comment]
已解决
