### ISSUE TITLE
Problem with multi jobs

### ISSUE THREAD

**Issue by tuanth89** [yigit/android-priority-jobqueue#48]
Hi @yigit, thanks for project.
I have 2 jobs call and run immediately when fragment instance. But only job 1 running, job 2 not working.
How to all jobs running ??
Thanks in advance

Update: After fix and change function of my project, job 2 worked but sometimes still not working.

In custom logger :

<pre><code>
D/JOBS: added job id: -2147483646 class: AllRecipesJob priority: 1 delay: 0 group : group1 persistent: false requires network: true
D/JOBS: SELECT * FROM job_holder WHERE _id IN ( SELECT job_id FROM job_holder_tags WHERE tag_name IN (?))
D/JOBS: running job AllRecipesJob
D/JOBS: pool-3-thread-1: load factor check. false = (1 < 1)|| (1 * 3 < 0 + 1). consumer thread: false
D/JOBS: added job id: -2147483645 class: AllVideosJob priority: 1 delay: 0 group : group2 persistent: false requires network: true
D/JOBS: pool-3-thread-1: load factor check. false = (1 < 1)|| (1 * 3 < 1 + 1). consumer thread: false
D/JOBS: finished job AllRecipesJob@422f6e90
D/JOBS: safeRunResult for AllRecipesJob@422f6e90 : true. re run:false. cancelled: false
D/JOBS: Thread-13293: load factor check. true = (0 < 1)|| (0 * 3 < 0 + 0). consumer thread: true
D/JOBS: didn't allow me to die, re-running Thread-13293
D/JOBS: re-running consumer Thread-13293

</code></pre>
- job 1 added and onRun
- job 2 added but not onRun

**Comment by yigit** [comment]
hmm, can you create a sample app ? From the log, looks like the 2nd job disappeared out of nowhere :/.

**Comment by tuanth89** [comment]
@yigit 
The problem sometimes happend. i can't handle it.
eg: i run app. 1, 2 in 10 times will not working(or always working) :(
Which way to resolve this problem  ???
sr about my bad english.

**Comment by tuanth89** [comment]
My project using GCM to receive notification.
when receive notify, i display Activity (A), A backpress to Activity (B). B wil call 2 jobs above and progress.

**Comment by yigit** [comment]
Can you also share the job? I would really like to dig into this as this is not acceptable if it is a library bug. 
I'm happy to look into it if you can share it w/ me in private if you cannot reproduce the issue in a separate app. Or maybe we can debug together via screenhero.

**Comment by tuanth89** [comment]
@yigit, thank for reply.
I fixed problem by call job 2 again. it worked for me but that's a temporary.
Maybe, i'll create sample, waiting for me. 
Thanks

**Comment by tuanth89** [comment]
i'll send my project to you as soon as possible. Could you please give me an email Address (Skype,..) ?

**Comment by tuanth89** [comment]
@yigit , i uploaded all code to bitbucket.org, do you have email or username bitbucket ???

**Comment by yigit** [comment]
yboyar [at] gmail. Thanks!

**Comment by tuanth89** [comment]
okay. i shared project, note 2 class: RecipeDetailActivity(first run) and HomeFragment(hosted by MainActivity)
When run first. RecipeDetailActivity called, press arrow back to HomeFragment. The problem above occurs.
I hope you understand i said :)
Thanks

**Comment by yigit** [comment]
Hmm, It seems to work fine here :/.

Below is my logs:
First start:

    D/JOBS    ( 7419): added job id: -2147483647 class: RecipeDetailJob priority: 1 delay: 0 group : null persistent: false requires network: true
    D/JOBS    ( 7419): pool-2-thread-1: load factor check. true = (0 < 1)|| (0 * 3 < 1 + 0). consumer thread: false
    D/JOBS    ( 7419): adding another consumer
    D/JOBS    ( 7419): starting consumer Thread-258
    D/JOBS    ( 7419): running job RecipeDetailJob
    D/JOBS    ( 7419): finished job com.teusoft.sousmatic.jobs.RecipeDetailJob@40a1886
    D/JOBS    ( 7419): safeRunResult for com.teusoft.sousmatic.jobs.RecipeDetailJob@40a1886 : true. re run:false. cancelled: false

Hit back:

    D/JOBS    ( 7419): added job id: -2147483646 class: AllRecipesJob priority: 1 delay: 0 group : group1 persistent: false requires network: true
    D/JOBS    ( 7419): running job AllRecipesJob
    D/JOBS    ( 7419): pool-2-thread-1: load factor check. false = (1 < 1)|| (1 * 3 < 0 + 1). consumer thread: false
    D/JOBS    ( 7419): added job id: -2147483645 class: AllVideosJob priority: 1 delay: 0 group : group2 persistent: false requires network: true
    D/JOBS    ( 7419): pool-2-thread-1: load factor check. false = (1 < 1)|| (1 * 3 < 1 + 1). consumer thread: false
    D/JOBS    ( 7419): finished job com.teusoft.sousmatic.jobs.AllRecipesJob@113802f4
    D/JOBS    ( 7419): safeRunResult for com.teusoft.sousmatic.jobs.AllRecipesJob@113802f4 : true. re run:false. cancelled: false
    D/JOBS    ( 7419): running job AllVideosJob
    D/JOBS    ( 7419): finished job com.teusoft.sousmatic.jobs.AllVideosJob@5a71fd5
    D/JOBS    ( 7419): safeRunResult for com.teusoft.sousmatic.jobs.AllVideosJob@5a71fd5 : true. re run:false. cancelled: false

Two jobs have been added on back and both of them did run :/. I'm testing w/ a N5 emulator, what is your test device ?

**Comment by tuanth89** [comment]
@yigit , thank for reply.
Did you try to many times (like exit app and run again) ? I also testing on N5 emulator, the problem occurred.
Thanks.

**Comment by yigit** [comment]
i tried 5 more times, same result. Btw, when I hit back, I also see this screen:

https://www.evernote.com/shard/s19/sh/d23deb37-facc-4ea5-9d23-03ff38ed4edd/4815ecdf5acd5a3b5160dab3faeb8c69 , maybe it is somehow preventing the error?

This is the error log:

    10-29 19:46:57.306  11915-12048/com.teusoft.sousmatic E/ACRA﹕ com.teusoft.sousmatic fatal error : An error occured while executing doInBackground()
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:304)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
            at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
            at com.teusoft.sousmatic.SousmaticApplication$4.doInBackground(SousmaticApplication.java:335)
            at com.teusoft.sousmatic.SousmaticApplication$4.doInBackground(SousmaticApplication.java:327)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)

Probably unrelated and happens because I'm running on an emulator w/o google services but just wanted to note here.

**Comment by yigit** [comment]
also i'm not seeing the SQL log in my logs.
That particular log in your log seems like coming from cancel jobs by tag request. Are you canceling jobs in some case that does not happen in my test?

**Comment by tuanth89** [comment]
@yigit, sorry. because your emulator missing google services :). okay. i'll fix and put to bitbucket and report you as soon as.

**Comment by tuanth89** [comment]
I don't cancel any jobs in app. I missing any things ???

**Comment by yigit** [comment]
i'm using android's default emulator. i will try with genymotion

**Comment by tuanth89** [comment]
@yigit ,
i don't know how to fix this problem. suggest or give me advice.
Thank so much
