### ISSUE TITLE
Persist Not working on Retrofit get Git user details

### ISSUE THREAD

**Issue by saran2somu** [yigit/android-priority-jobqueue#52]
Hi , 

 In my code non persistent ( new Params(1).requireNetwork() ) in working correctly and fast . But I have add the persistent in code , it not working and shows the below logcat output. 

My code : 
package com.az.service;

import com.az.dbhelper.DbHelper;
import com.az.model.api.Gitapi;
import com.az.model.entity.User;
import com.az.networkutil.RetrofitClient;
import com.az.ormmodel.GitUser;
import com.az.ormmodel.GitUserModel;
import com.path.android.jobqueue.Job;
import com.path.android.jobqueue.JobManager;
import com.path.android.jobqueue.Params;

import java.util.Date;

import de.greenrobot.event.EventBus;
import retrofit.Call;
import retrofit.Callback;
import retrofit.Retrofit;

/**
 * Created by mobilepc1 on 11/12/15.
 */
public class GetGitUsers extends Job {

    //Notes : Use the persistent - store the values in disk (SQLITE) and then get and update the Value ,
    // because it uses for re try and re post while app restart
    DbHelper  dbHelper ;

    private long localId;
    String userName;
    GetGitUserEvent gitUserEvent;
    private EventBus bus = EventBus.getDefault();
    public GetGitUsers(String userName)
    {
        super(new Params(1).requireNetwork().persist());
        this.userName =userName;
        localId = -System.currentTimeMillis();
        dbHelper =DbHelper.getInstance();
    }
    /**
     * Called when the job is added to disk and committed.
     * This means job will eventually run. This is a good time to update local database and dispatch events.
     * <p/>
     * Changes to this class will not be preserved if your job is persistent !!!
     * <p/>
     * Also, if your app crashes right after adding the job, {@code onRun} might be called without an {@code onAdded} call
     * <p/>
     * Note that this method is called on the thread the job is added. (e.g. {@link JobManager#addJob(Job)})
     * is called. If job was added via {@link  JobManager#addJobInBackground(Job)} or
     * , it will be run on JobManager's
     * utility thread.
     */
    @Override
    public void onAdded() {

        GitUser gitUser =new GitUser(localId,userName,new Date(System.currentTimeMillis()));

        dbHelper.getDaoSession().getGitUserDao().insertOrReplace(gitUser);
    }

    /**
     * The actual method that should to the work.
     * It should finish w/o any exception. If it throws any exception,
     * {@link #shouldReRunOnThrowable(Throwable, int, int)} will be called to
     * decide either to dismiss the job or re-run it.
     *
     * @throws Throwable
     */
    @Override
    public void onRun() throws Throwable {

        GitUserModel tweetModel = GitUserModel.getInstance();
        GitUser  gitUser =tweetModel.getUserLocalId(localId);
        if(gitUser!=null){
            dbHelper.getDaoSession().getGitUserDao().insertOrReplace(gitUser);
        }

        RetrofitClient retrofitClient =new RetrofitClient();
        Gitapi gitService= retrofitClient.getRetrofit().create(Gitapi.class);
        Call<User> userCall =gitService.getFeed(gitUser.getUserName());
        userCall.enqueue(new Callback<User>() {
            @Override
            public void onResponse(retrofit.Response<User> response, Retrofit retrofit) {
                gitUserEvent = new GetGitUserEvent(response);
                bus.post(gitUserEvent);
            }

            @Override
            public void onFailure(Throwable t) {
                gitUserEvent = new GetGitUserEvent(t.getMessage());
                bus.post(gitUserEvent);
            }

        });

    }

    /**
     * Called when a job is cancelled.
     */
    @Override
    protected void onCancel() {

    }

}

My Logcat Error : 
11-16 18:42:25.667  16416-16540/com.assistanz.aztracking E/JOBS﹕ error while serializing object GetGitUsers
    java.io.NotSerializableException: de.greenrobot.event.EventBus
            at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
            at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
            at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
            at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
            at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
            at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
            at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
            at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
            at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
            at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
            at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
            at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue$JavaSerializer.serialize(SqliteJobQueue.java:460)
            at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.safeSerialize(SqliteJobQueue.java:437)
            at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.getSerializeJob(SqliteJobQueue.java:432)
            at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.bindValues(SqliteJobQueue.java:116)
            at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.insert(SqliteJobQueue.java:71)
            at com.path.android.jobqueue.cachedQueue.CachedJobQueue.insert(CachedJobQueue.java:30)
            at com.path.android.jobqueue.JobManager.addJob(JobManager.java:166)
            at com.path.android.jobqueue.JobManager$3.run(JobManager.java:397)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
11-16 18:42:25.682  16416-16540/com.assistanz.aztracking D/JOBS﹕ added job id: 14 class: GetGitUsers priority: 1 delay: 0 group : null persistent: true requires network: true
11-16 18:42:25.686  16416-16540/com.assistanz.aztracking D/JOBS﹕ pool-1-thread-1: load factor check. true = (0 < 1)|| (0 * 3 < 1 + 0). consumer thread: false
11-16 18:42:25.686  16416-16540/com.assistanz.aztracking D/JOBS﹕ adding another consumer
11-16 18:42:25.688  16416-16546/com.assistanz.aztracking D/JOBS﹕ starting consumer Thread-688
11-16 18:42:25.689  16416-16546/com.assistanz.aztracking D/JOBS﹕ looking for next job
11-16 18:42:25.689  16416-16546/com.assistanz.aztracking D/JOBS﹕ running groups
11-16 18:42:25.689  16416-16546/com.assistanz.aztracking D/JOBS﹕ non persistent result null
11-16 18:42:25.706  16416-16546/com.assistanz.aztracking D/JOBS﹕ persistent result null
11-16 18:42:25.708  16416-16546/com.assistanz.aztracking D/JOBS﹕ Thread-688: load factor check. false = (1 < 1)|| (1 * 3 < 0 + 0). consumer thread: false
11-16 18:42:25.709  16416-16546/com.assistanz.aztracking D/JOBS﹕ looking for next job
11-16 18:42:25.709  16416-16546/com.assistanz.aztracking D/JOBS﹕ running groups
11-16 18:42:25.709  16416-16546/com.assistanz.aztracking D/JOBS﹕ non persistent result null
11-16 18:42:25.709  16416-16546/com.assistanz.aztracking D/JOBS﹕ persistent result null
11-16 18:42:25.710  16416-16546/com.assistanz.aztracking D/JOBS﹕ looking for next job
11-16 18:42:25.710  16416-16546/com.assistanz.aztracking D/JOBS﹕ running groups
11-16 18:42:25.710  16416-16546/com.assistanz.aztracking D/JOBS﹕ non persistent result null
11-16 18:42:25.710  16416-16546/com.assistanz.aztracking D/JOBS﹕ persistent result null
11-16 18:42:25.711  16416-16546/com.assistanz.aztracking D/JOBS﹕ looking for next job
11-16 18:42:25.711  16416-16546/com.assistanz.aztracking D/JOBS﹕ running groups
11-16 18:42:25.711  16416-16546/com.assistanz.aztracking D/JOBS﹕ non persistent result null
11-16 18:42:25.711  16416-16546/com.assistanz.aztracking D/JOBS﹕ persistent result null
11-16 18:42:25.713  16416-16546/com.assistanz.aztracking D/JOBS﹕ looking for next job
11-16 18:42:25.713  16416-16546/com.assistanz.aztracking D/JOBS﹕ running groups
11-16 18:42:25.713  16416-16546/com.assistanz.aztracking D/JOBS﹕ non persistent result null
11-16 18:42:25.713  16416-16546/com.assistanz.aztracking D/JOBS﹕ persistent result null
11-16 18:42:25.714  16416-16546/com.assistanz.aztracking D/JOBS﹕ looking for next job
11-16 18:42:25.714  16416-16546/com.assistanz.aztracking D/JOBS﹕ running groups
11-16 18:42:25.714  16416-16546/com.assistanz.aztracking D/JOBS﹕ non persistent result null
11-16 18:42:25.714  16416-16546/com.assistanz.aztracking D/JOBS﹕ persistent result null
11-16 18:42:25.714  16416-16546/com.assistanz.aztracking D/JOBS﹕ looking for next job
11-16 18:42:25.714  16416-16546/com.assistanz.aztracking D/JOBS﹕ running groups
11-16 18:42:25.714  16416-16546/com.assistanz.aztracking D/JOBS﹕ non persistent result null
11-16 18:42:25.714  16416-16546/com.assistanz.aztracking D/JOBS﹕ persistent result null
11-16 18:42:25.715  16416-16546/com.assistanz.aztracking D/JOBS﹕ looking for next job
11-16 18:42:25.715  16416-16546/com.assistanz.aztracking D/JOBS﹕ running groups
.
.
.

**Comment by mseshachalam** [comment]
```
private EventBus bus = EventBus.getDefault(); 
```
Is not serializable. You have to make it transient, like ```transient private EventBus bus;```

**Comment by saran2somu** [comment]
Thanks mseshachalam , I have update the code  I test using Android 6.0 Nexus 5, But got error 

11-17 16:42:52.419    1222-1855/com.assistanz.aztracking E/JOBS﹕ error while serializing object GetGitUsers
    java.io.NotSerializableException: com.assistanz.dbhelper.DbHelper
            at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
            at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
            at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
            at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
            at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
            at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
            at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
            at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
            at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
            at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
            at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
            at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue$JavaSerializer.serialize(SqliteJobQueue.java:460)
            at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.safeSerialize(SqliteJobQueue.java:437)
            at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.getSerializeJob(SqliteJobQueue.java:432)
            at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.bindValues(SqliteJobQueue.java:116)
            at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.insert(SqliteJobQueue.java:71)
            at com.path.android.jobqueue.cachedQueue.CachedJobQueue.insert(CachedJobQueue.java:30)
            at com.path.android.jobqueue.JobManager.addJob(JobManager.java:166)
            at com.path.android.jobqueue.JobManager$3.run(JobManager.java:397)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
11-17 16:42:52.440    1222-1855/com.assistanz.aztracking D/JOBS﹕ added job id: 21 class: GetGitUsers priority: 1 delay: 0 group : null persistent: true requires network: true
11-17 16:42:52.443    1222-1855/com.assistanz.aztracking D/JOBS﹕ pool-1-thread-1: load factor check. true = (0 < 1)|| (0 * 3 < 1 + 0). consumer thread: false
11-17 16:42:52.443    1222-1855/com.assistanz.aztracking D/JOBS﹕ adding another consumer
11-17 16:42:52.445    1222-1857/com.assistanz.aztracking D/JOBS﹕ starting consumer Thread-1215
11-17 16:42:52.446    1222-1857/com.assistanz.aztracking D/JOBS﹕ looking for next job
11-17 16:42:52.446    1222-1857/com.assistanz.aztracking D/JOBS﹕ running groups
11-17 16:42:52.446    1222-1857/com.assistanz.aztracking D/JOBS﹕ non persistent result null
11-17 16:42:52.479    1222-1857/com.assistanz.aztracking D/JOBS﹕ persistent result null
11-17 16:42:52.483    1222-1857/com.assistanz.aztracking D/JOBS﹕ Thread-1215: load factor check. false = (1 < 1)|| (1 * 3 < 0 + 0). consumer thread: false
11-17 16:42:52.483    1222-1857/com.assistanz.aztracking D/JOBS﹕ looking for next job
11-17 16:42:52.483    1222-1857/com.assistanz.aztracking D/JOBS﹕ running groups

**Comment by mseshachalam** [comment]
@saran2somu I am sorry to be blunt but I too no expert on these matters but if you look at the stack trace it says exactly whats wrong i.e  DbHelper dbHelper is not serializable which is the same issue as before.
